### YamlMime:ManagedReference
items:
- uid: DynamoForRevitUtils.Entities.Wrappers
  commentId: N:DynamoForRevitUtils.Entities.Wrappers
  id: DynamoForRevitUtils.Entities.Wrappers
  children:
  - DynamoForRevitUtils.Entities.Wrappers.ElementWrapper`1
  - DynamoForRevitUtils.Entities.Wrappers.FamilyInstanceWrapper`1
  - DynamoForRevitUtils.Entities.Wrappers.IElementWrapper`1
  langs:
  - csharp
  - vb
  name: DynamoForRevitUtils.Entities.Wrappers
  nameWithType: DynamoForRevitUtils.Entities.Wrappers
  fullName: DynamoForRevitUtils.Entities.Wrappers
  type: Namespace
  assemblies:
  - DynamoForRevitUtils
references:
- uid: DynamoForRevitUtils.Entities.Wrappers.ElementWrapper`1
  commentId: T:DynamoForRevitUtils.Entities.Wrappers.ElementWrapper`1
  isExternal: true
  href: DynamoForRevitUtils.Entities.Wrappers.ElementWrapper-1.html
  name: ElementWrapper<TParamMap>
  nameWithType: ElementWrapper<TParamMap>
  fullName: DynamoForRevitUtils.Entities.Wrappers.ElementWrapper<TParamMap>
  nameWithType.vb: ElementWrapper(Of TParamMap)
  fullName.vb: DynamoForRevitUtils.Entities.Wrappers.ElementWrapper(Of TParamMap)
  name.vb: ElementWrapper(Of TParamMap)
  spec.csharp:
  - uid: DynamoForRevitUtils.Entities.Wrappers.ElementWrapper`1
    name: ElementWrapper
    isExternal: true
    href: DynamoForRevitUtils.Entities.Wrappers.ElementWrapper-1.html
  - name: <
  - name: TParamMap
  - name: '>'
  spec.vb:
  - uid: DynamoForRevitUtils.Entities.Wrappers.ElementWrapper`1
    name: ElementWrapper
    isExternal: true
    href: DynamoForRevitUtils.Entities.Wrappers.ElementWrapper-1.html
  - name: (
  - name: Of
  - name: " "
  - name: TParamMap
  - name: )
- uid: DynamoForRevitUtils.Entities.Wrappers.FamilyInstanceWrapper`1
  commentId: T:DynamoForRevitUtils.Entities.Wrappers.FamilyInstanceWrapper`1
  isExternal: true
  href: DynamoForRevitUtils.Entities.Wrappers.FamilyInstanceWrapper-1.html
  name: FamilyInstanceWrapper<TParamMap>
  nameWithType: FamilyInstanceWrapper<TParamMap>
  fullName: DynamoForRevitUtils.Entities.Wrappers.FamilyInstanceWrapper<TParamMap>
  nameWithType.vb: FamilyInstanceWrapper(Of TParamMap)
  fullName.vb: DynamoForRevitUtils.Entities.Wrappers.FamilyInstanceWrapper(Of TParamMap)
  name.vb: FamilyInstanceWrapper(Of TParamMap)
  spec.csharp:
  - uid: DynamoForRevitUtils.Entities.Wrappers.FamilyInstanceWrapper`1
    name: FamilyInstanceWrapper
    isExternal: true
    href: DynamoForRevitUtils.Entities.Wrappers.FamilyInstanceWrapper-1.html
  - name: <
  - name: TParamMap
  - name: '>'
  spec.vb:
  - uid: DynamoForRevitUtils.Entities.Wrappers.FamilyInstanceWrapper`1
    name: FamilyInstanceWrapper
    isExternal: true
    href: DynamoForRevitUtils.Entities.Wrappers.FamilyInstanceWrapper-1.html
  - name: (
  - name: Of
  - name: " "
  - name: TParamMap
  - name: )
- uid: DynamoForRevitUtils.Entities.Wrappers.IElementWrapper`1
  commentId: T:DynamoForRevitUtils.Entities.Wrappers.IElementWrapper`1
  isExternal: true
  href: DynamoForRevitUtils.Entities.Wrappers.IElementWrapper-1.html
  name: IElementWrapper<TParamMap>
  nameWithType: IElementWrapper<TParamMap>
  fullName: DynamoForRevitUtils.Entities.Wrappers.IElementWrapper<TParamMap>
  nameWithType.vb: IElementWrapper(Of TParamMap)
  fullName.vb: DynamoForRevitUtils.Entities.Wrappers.IElementWrapper(Of TParamMap)
  name.vb: IElementWrapper(Of TParamMap)
  spec.csharp:
  - uid: DynamoForRevitUtils.Entities.Wrappers.IElementWrapper`1
    name: IElementWrapper
    isExternal: true
    href: DynamoForRevitUtils.Entities.Wrappers.IElementWrapper-1.html
  - name: <
  - name: TParamMap
  - name: '>'
  spec.vb:
  - uid: DynamoForRevitUtils.Entities.Wrappers.IElementWrapper`1
    name: IElementWrapper
    isExternal: true
    href: DynamoForRevitUtils.Entities.Wrappers.IElementWrapper-1.html
  - name: (
  - name: Of
  - name: " "
  - name: TParamMap
  - name: )
