### YamlMime:ManagedReference
items:
- uid: DynamoForRevitUtils.Entities.ParametersHandlers
  commentId: N:DynamoForRevitUtils.Entities.ParametersHandlers
  id: DynamoForRevitUtils.Entities.ParametersHandlers
  children:
  - DynamoForRevitUtils.Entities.ParametersHandlers.AccessParameterInfo
  - DynamoForRevitUtils.Entities.ParametersHandlers.AccessParameterOptions
  - DynamoForRevitUtils.Entities.ParametersHandlers.ElementParameter
  - DynamoForRevitUtils.Entities.ParametersHandlers.ElementParameterAccessor`1
  - DynamoForRevitUtils.Entities.ParametersHandlers.ElementParameters`1
  - DynamoForRevitUtils.Entities.ParametersHandlers.IElementParameters
  - DynamoForRevitUtils.Entities.ParametersHandlers.PropertyParameterBinding
  langs:
  - csharp
  - vb
  name: DynamoForRevitUtils.Entities.ParametersHandlers
  nameWithType: DynamoForRevitUtils.Entities.ParametersHandlers
  fullName: DynamoForRevitUtils.Entities.ParametersHandlers
  type: Namespace
  assemblies:
  - DynamoForRevitUtils
references:
- uid: DynamoForRevitUtils.Entities.ParametersHandlers.AccessParameterInfo
  commentId: T:DynamoForRevitUtils.Entities.ParametersHandlers.AccessParameterInfo
  parent: DynamoForRevitUtils.Entities.ParametersHandlers
  isExternal: true
  href: DynamoForRevitUtils.Entities.ParametersHandlers.AccessParameterInfo.html
  name: AccessParameterInfo
  nameWithType: AccessParameterInfo
  fullName: DynamoForRevitUtils.Entities.ParametersHandlers.AccessParameterInfo
- uid: DynamoForRevitUtils.Entities.ParametersHandlers.AccessParameterOptions
  commentId: T:DynamoForRevitUtils.Entities.ParametersHandlers.AccessParameterOptions
  parent: DynamoForRevitUtils.Entities.ParametersHandlers
  isExternal: true
  href: DynamoForRevitUtils.Entities.ParametersHandlers.AccessParameterOptions.html
  name: AccessParameterOptions
  nameWithType: AccessParameterOptions
  fullName: DynamoForRevitUtils.Entities.ParametersHandlers.AccessParameterOptions
- uid: DynamoForRevitUtils.Entities.ParametersHandlers.ElementParameter
  commentId: T:DynamoForRevitUtils.Entities.ParametersHandlers.ElementParameter
  parent: DynamoForRevitUtils.Entities.ParametersHandlers
  isExternal: true
  href: DynamoForRevitUtils.Entities.ParametersHandlers.ElementParameter.html
  name: ElementParameter
  nameWithType: ElementParameter
  fullName: DynamoForRevitUtils.Entities.ParametersHandlers.ElementParameter
- uid: DynamoForRevitUtils.Entities.ParametersHandlers.ElementParameterAccessor`1
  commentId: T:DynamoForRevitUtils.Entities.ParametersHandlers.ElementParameterAccessor`1
  isExternal: true
  href: DynamoForRevitUtils.Entities.ParametersHandlers.ElementParameterAccessor-1.html
  name: ElementParameterAccessor<TParams>
  nameWithType: ElementParameterAccessor<TParams>
  fullName: DynamoForRevitUtils.Entities.ParametersHandlers.ElementParameterAccessor<TParams>
  nameWithType.vb: ElementParameterAccessor(Of TParams)
  fullName.vb: DynamoForRevitUtils.Entities.ParametersHandlers.ElementParameterAccessor(Of TParams)
  name.vb: ElementParameterAccessor(Of TParams)
  spec.csharp:
  - uid: DynamoForRevitUtils.Entities.ParametersHandlers.ElementParameterAccessor`1
    name: ElementParameterAccessor
    isExternal: true
    href: DynamoForRevitUtils.Entities.ParametersHandlers.ElementParameterAccessor-1.html
  - name: <
  - name: TParams
  - name: '>'
  spec.vb:
  - uid: DynamoForRevitUtils.Entities.ParametersHandlers.ElementParameterAccessor`1
    name: ElementParameterAccessor
    isExternal: true
    href: DynamoForRevitUtils.Entities.ParametersHandlers.ElementParameterAccessor-1.html
  - name: (
  - name: Of
  - name: " "
  - name: TParams
  - name: )
- uid: DynamoForRevitUtils.Entities.ParametersHandlers.ElementParameters`1
  commentId: T:DynamoForRevitUtils.Entities.ParametersHandlers.ElementParameters`1
  isExternal: true
  href: DynamoForRevitUtils.Entities.ParametersHandlers.ElementParameters-1.html
  name: ElementParameters<T>
  nameWithType: ElementParameters<T>
  fullName: DynamoForRevitUtils.Entities.ParametersHandlers.ElementParameters<T>
  nameWithType.vb: ElementParameters(Of T)
  fullName.vb: DynamoForRevitUtils.Entities.ParametersHandlers.ElementParameters(Of T)
  name.vb: ElementParameters(Of T)
  spec.csharp:
  - uid: DynamoForRevitUtils.Entities.ParametersHandlers.ElementParameters`1
    name: ElementParameters
    isExternal: true
    href: DynamoForRevitUtils.Entities.ParametersHandlers.ElementParameters-1.html
  - name: <
  - name: T
  - name: '>'
  spec.vb:
  - uid: DynamoForRevitUtils.Entities.ParametersHandlers.ElementParameters`1
    name: ElementParameters
    isExternal: true
    href: DynamoForRevitUtils.Entities.ParametersHandlers.ElementParameters-1.html
  - name: (
  - name: Of
  - name: " "
  - name: T
  - name: )
- uid: DynamoForRevitUtils.Entities.ParametersHandlers.IElementParameters
  commentId: T:DynamoForRevitUtils.Entities.ParametersHandlers.IElementParameters
  parent: DynamoForRevitUtils.Entities.ParametersHandlers
  isExternal: true
  href: DynamoForRevitUtils.Entities.ParametersHandlers.IElementParameters.html
  name: IElementParameters
  nameWithType: IElementParameters
  fullName: DynamoForRevitUtils.Entities.ParametersHandlers.IElementParameters
- uid: DynamoForRevitUtils.Entities.ParametersHandlers.PropertyParameterBinding
  commentId: T:DynamoForRevitUtils.Entities.ParametersHandlers.PropertyParameterBinding
  isExternal: true
  href: DynamoForRevitUtils.Entities.ParametersHandlers.PropertyParameterBinding.html
  name: PropertyParameterBinding
  nameWithType: PropertyParameterBinding
  fullName: DynamoForRevitUtils.Entities.ParametersHandlers.PropertyParameterBinding
- uid: DynamoForRevitUtils.Entities.ParametersHandlers
  commentId: N:DynamoForRevitUtils.Entities.ParametersHandlers
  isExternal: true
  href: DynamoForRevitUtils.html
  name: DynamoForRevitUtils.Entities.ParametersHandlers
  nameWithType: DynamoForRevitUtils.Entities.ParametersHandlers
  fullName: DynamoForRevitUtils.Entities.ParametersHandlers
  spec.csharp:
  - uid: DynamoForRevitUtils
    name: DynamoForRevitUtils
    isExternal: true
    href: DynamoForRevitUtils.html
  - name: .
  - uid: DynamoForRevitUtils.Entities
    name: Entities
    isExternal: true
    href: DynamoForRevitUtils.Entities.html
  - name: .
  - uid: DynamoForRevitUtils.Entities.ParametersHandlers
    name: ParametersHandlers
    isExternal: true
    href: DynamoForRevitUtils.Entities.ParametersHandlers.html
  spec.vb:
  - uid: DynamoForRevitUtils
    name: DynamoForRevitUtils
    isExternal: true
    href: DynamoForRevitUtils.html
  - name: .
  - uid: DynamoForRevitUtils.Entities
    name: Entities
    isExternal: true
    href: DynamoForRevitUtils.Entities.html
  - name: .
  - uid: DynamoForRevitUtils.Entities.ParametersHandlers
    name: ParametersHandlers
    isExternal: true
    href: DynamoForRevitUtils.Entities.ParametersHandlers.html
