### YamlMime:ManagedReference
items:
- uid: DynamoForRevitUtils.Services.Dynamo.JoinLinesServices
  commentId: T:DynamoForRevitUtils.Services.Dynamo.JoinLinesServices
  id: JoinLinesServices
  parent: DynamoForRevitUtils.Services.Dynamo
  children:
  - DynamoForRevitUtils.Services.Dynamo.JoinLinesServices.JoinLinesIntoClosedPolyCurve(System.Collections.Generic.List{Autodesk.DesignScript.Geometry.Line},System.Boolean)
  langs:
  - csharp
  - vb
  name: JoinLinesServices
  nameWithType: JoinLinesServices
  fullName: DynamoForRevitUtils.Services.Dynamo.JoinLinesServices
  type: Class
  assemblies:
  - DynamoForRevitUtils
  namespace: DynamoForRevitUtils.Services.Dynamo
  summary: Join Lines Services
  remarks: >-
    <p>Based on Spring Nodes Functions - LineLoop.Merge. by Dimitar Venkov.</p>

    <p>@5devene | dimitar.ven@gmail.com</p>
  example: []
  syntax:
    content: public static class JoinLinesServices
    content.vb: Public Module JoinLinesServices
  inheritance:
  - System.Object
  inheritedMembers:
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ToString
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.GetHashCode
- uid: DynamoForRevitUtils.Services.Dynamo.JoinLinesServices.JoinLinesIntoClosedPolyCurve(System.Collections.Generic.List{Autodesk.DesignScript.Geometry.Line},System.Boolean)
  commentId: M:DynamoForRevitUtils.Services.Dynamo.JoinLinesServices.JoinLinesIntoClosedPolyCurve(System.Collections.Generic.List{Autodesk.DesignScript.Geometry.Line},System.Boolean)
  id: JoinLinesIntoClosedPolyCurve(System.Collections.Generic.List{Autodesk.DesignScript.Geometry.Line},System.Boolean)
  parent: DynamoForRevitUtils.Services.Dynamo.JoinLinesServices
  langs:
  - csharp
  - vb
  name: JoinLinesIntoClosedPolyCurve(List<Line>, bool)
  nameWithType: JoinLinesServices.JoinLinesIntoClosedPolyCurve(List<Line>, bool)
  fullName: DynamoForRevitUtils.Services.Dynamo.JoinLinesServices.JoinLinesIntoClosedPolyCurve(System.Collections.Generic.List<Autodesk.DesignScript.Geometry.Line>, bool)
  type: Method
  assemblies:
  - DynamoForRevitUtils
  namespace: DynamoForRevitUtils.Services.Dynamo
  summary: Joins a collection of lines into a closed <xref href="Autodesk.DesignScript.Geometry.PolyCurve" data-throw-if-not-resolved="false"></xref>.
  example: []
  syntax:
    content: public static PolyCurve JoinLinesIntoClosedPolyCurve(List<Line> lines, bool tryReorderLines = true)
    parameters:
    - id: lines
      type: System.Collections.Generic.List{Autodesk.DesignScript.Geometry.Line}
      description: The collection of lines to join.
    - id: tryReorderLines
      type: System.Boolean
      description: >-
        Optional. Specifies whether to try to reorder the lines before joining. Default is true.

        Use this option when the lines are not in the correct order to form a closed loop.
    return:
      type: Autodesk.DesignScript.Geometry.PolyCurve
      description: A closed <xref href="Autodesk.DesignScript.Geometry.PolyCurve" data-throw-if-not-resolved="false"></xref> formed by joining the lines.
    content.vb: Public Shared Function JoinLinesIntoClosedPolyCurve(lines As List(Of Line), tryReorderLines As Boolean = True) As PolyCurve
  overload: DynamoForRevitUtils.Services.Dynamo.JoinLinesServices.JoinLinesIntoClosedPolyCurve*
  exceptions:
  - type: System.ArgumentException
    commentId: T:System.ArgumentException
    description: Thrown when the collection of lines is empty.
  - type: System.Exception
    commentId: T:System.Exception
    description: Thrown when the number of lines is not enough to form a closed loop.
  - type: System.Exception
    commentId: T:System.Exception
    description: Thrown when was not possible to connect all lines.
  nameWithType.vb: JoinLinesServices.JoinLinesIntoClosedPolyCurve(List(Of Line), Boolean)
  fullName.vb: DynamoForRevitUtils.Services.Dynamo.JoinLinesServices.JoinLinesIntoClosedPolyCurve(System.Collections.Generic.List(Of Autodesk.DesignScript.Geometry.Line), Boolean)
  name.vb: JoinLinesIntoClosedPolyCurve(List(Of Line), Boolean)
references:
- uid: DynamoForRevitUtils.Services.Dynamo
  commentId: N:DynamoForRevitUtils.Services.Dynamo
  isExternal: true
  href: DynamoForRevitUtils.html
  name: DynamoForRevitUtils.Services.Dynamo
  nameWithType: DynamoForRevitUtils.Services.Dynamo
  fullName: DynamoForRevitUtils.Services.Dynamo
  spec.csharp:
  - uid: DynamoForRevitUtils
    name: DynamoForRevitUtils
    isExternal: true
    href: DynamoForRevitUtils.html
  - name: .
  - uid: DynamoForRevitUtils.Services
    name: Services
    isExternal: true
    href: DynamoForRevitUtils.Services.html
  - name: .
  - uid: DynamoForRevitUtils.Services.Dynamo
    name: Dynamo
    isExternal: true
    href: DynamoForRevitUtils.Services.Dynamo.html
  spec.vb:
  - uid: DynamoForRevitUtils
    name: DynamoForRevitUtils
    isExternal: true
    href: DynamoForRevitUtils.html
  - name: .
  - uid: DynamoForRevitUtils.Services
    name: Services
    isExternal: true
    href: DynamoForRevitUtils.Services.html
  - name: .
  - uid: DynamoForRevitUtils.Services.Dynamo
    name: Dynamo
    isExternal: true
    href: DynamoForRevitUtils.Services.Dynamo.html
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object
  name: object
  nameWithType: object
  fullName: object
  nameWithType.vb: Object
  fullName.vb: Object
  name.vb: Object
- uid: System.Object.GetType
  commentId: M:System.Object.GetType
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  name: GetType()
  nameWithType: object.GetType()
  fullName: object.GetType()
  nameWithType.vb: Object.GetType()
  fullName.vb: Object.GetType()
  spec.csharp:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
- uid: System.Object.MemberwiseClone
  commentId: M:System.Object.MemberwiseClone
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  name: MemberwiseClone()
  nameWithType: object.MemberwiseClone()
  fullName: object.MemberwiseClone()
  nameWithType.vb: Object.MemberwiseClone()
  fullName.vb: Object.MemberwiseClone()
  spec.csharp:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  - name: (
  - name: )
- uid: System.Object.ToString
  commentId: M:System.Object.ToString
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  name: ToString()
  nameWithType: object.ToString()
  fullName: object.ToString()
  nameWithType.vb: Object.ToString()
  fullName.vb: Object.ToString()
  spec.csharp:
  - uid: System.Object.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  - name: (
  - name: )
- uid: System.Object.Equals(System.Object)
  commentId: M:System.Object.Equals(System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  name: Equals(object)
  nameWithType: object.Equals(object)
  fullName: object.Equals(object)
  nameWithType.vb: Object.Equals(Object)
  fullName.vb: Object.Equals(Object)
  name.vb: Equals(Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.Equals(System.Object,System.Object)
  commentId: M:System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  name: Equals(object, object)
  nameWithType: object.Equals(object, object)
  fullName: object.Equals(object, object)
  nameWithType.vb: Object.Equals(Object, Object)
  fullName.vb: Object.Equals(Object, Object)
  name.vb: Equals(Object, Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  commentId: M:System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  name: ReferenceEquals(object, object)
  nameWithType: object.ReferenceEquals(object, object)
  fullName: object.ReferenceEquals(object, object)
  nameWithType.vb: Object.ReferenceEquals(Object, Object)
  fullName.vb: Object.ReferenceEquals(Object, Object)
  name.vb: ReferenceEquals(Object, Object)
  spec.csharp:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.GetHashCode
  commentId: M:System.Object.GetHashCode
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  name: GetHashCode()
  nameWithType: object.GetHashCode()
  fullName: object.GetHashCode()
  nameWithType.vb: Object.GetHashCode()
  fullName.vb: Object.GetHashCode()
  spec.csharp:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  - name: (
  - name: )
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: Autodesk.DesignScript.Geometry.PolyCurve
  isExternal: true
  name: PolyCurve
  nameWithType: PolyCurve
  fullName: Autodesk.DesignScript.Geometry.PolyCurve
- uid: System.ArgumentException
  commentId: T:System.ArgumentException
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.argumentexception
  name: ArgumentException
  nameWithType: ArgumentException
  fullName: System.ArgumentException
- uid: System.Exception
  commentId: T:System.Exception
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.exception
  name: Exception
  nameWithType: Exception
  fullName: System.Exception
- uid: DynamoForRevitUtils.Services.Dynamo.JoinLinesServices.JoinLinesIntoClosedPolyCurve*
  commentId: Overload:DynamoForRevitUtils.Services.Dynamo.JoinLinesServices.JoinLinesIntoClosedPolyCurve
  isExternal: true
  href: DynamoForRevitUtils.Services.Dynamo.JoinLinesServices.html#DynamoForRevitUtils_Services_Dynamo_JoinLinesServices_JoinLinesIntoClosedPolyCurve_System_Collections_Generic_List_Autodesk_DesignScript_Geometry_Line__System_Boolean_
  name: JoinLinesIntoClosedPolyCurve
  nameWithType: JoinLinesServices.JoinLinesIntoClosedPolyCurve
  fullName: DynamoForRevitUtils.Services.Dynamo.JoinLinesServices.JoinLinesIntoClosedPolyCurve
- uid: System.Collections.Generic.List{Autodesk.DesignScript.Geometry.Line}
  commentId: T:System.Collections.Generic.List{Autodesk.DesignScript.Geometry.Line}
  parent: System.Collections.Generic
  definition: System.Collections.Generic.List`1
  href: https://learn.microsoft.com/dotnet/api/system.collections.generic.list-1
  name: List<Line>
  nameWithType: List<Line>
  fullName: System.Collections.Generic.List<Autodesk.DesignScript.Geometry.Line>
  nameWithType.vb: List(Of Line)
  fullName.vb: System.Collections.Generic.List(Of Autodesk.DesignScript.Geometry.Line)
  name.vb: List(Of Line)
  spec.csharp:
  - uid: System.Collections.Generic.List`1
    name: List
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections.generic.list-1
  - name: <
  - uid: Autodesk.DesignScript.Geometry.Line
    name: Line
    isExternal: true
  - name: '>'
  spec.vb:
  - uid: System.Collections.Generic.List`1
    name: List
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections.generic.list-1
  - name: (
  - name: Of
  - name: " "
  - uid: Autodesk.DesignScript.Geometry.Line
    name: Line
    isExternal: true
  - name: )
- uid: System.Boolean
  commentId: T:System.Boolean
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.boolean
  name: bool
  nameWithType: bool
  fullName: bool
  nameWithType.vb: Boolean
  fullName.vb: Boolean
  name.vb: Boolean
- uid: System.Collections.Generic.List`1
  commentId: T:System.Collections.Generic.List`1
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.collections.generic.list-1
  name: List<T>
  nameWithType: List<T>
  fullName: System.Collections.Generic.List<T>
  nameWithType.vb: List(Of T)
  fullName.vb: System.Collections.Generic.List(Of T)
  name.vb: List(Of T)
  spec.csharp:
  - uid: System.Collections.Generic.List`1
    name: List
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections.generic.list-1
  - name: <
  - name: T
  - name: '>'
  spec.vb:
  - uid: System.Collections.Generic.List`1
    name: List
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections.generic.list-1
  - name: (
  - name: Of
  - name: " "
  - name: T
  - name: )
- uid: System.Collections.Generic
  commentId: N:System.Collections.Generic
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System.Collections.Generic
  nameWithType: System.Collections.Generic
  fullName: System.Collections.Generic
  spec.csharp:
  - uid: System
    name: System
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system
  - name: .
  - uid: System.Collections
    name: Collections
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections
  - name: .
  - uid: System.Collections.Generic
    name: Generic
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections.generic
  spec.vb:
  - uid: System
    name: System
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system
  - name: .
  - uid: System.Collections
    name: Collections
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections
  - name: .
  - uid: System.Collections.Generic
    name: Generic
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections.generic
