### YamlMime:ManagedReference
items:
- uid: DynamoForRevitUtils.Services.Collectors.LineStyleCollectors
  commentId: T:DynamoForRevitUtils.Services.Collectors.LineStyleCollectors
  id: LineStyleCollectors
  parent: DynamoForRevitUtils.Services.Collectors
  children:
  - DynamoForRevitUtils.Services.Collectors.LineStyleCollectors.AllCutStyles(Autodesk.Revit.DB.Document)
  - DynamoForRevitUtils.Services.Collectors.LineStyleCollectors.AllProjectionStyles(Autodesk.Revit.DB.Document)
  langs:
  - csharp
  - vb
  name: LineStyleCollectors
  nameWithType: LineStyleCollectors
  fullName: DynamoForRevitUtils.Services.Collectors.LineStyleCollectors
  type: Class
  assemblies:
  - DynamoForRevitUtils
  namespace: DynamoForRevitUtils.Services.Collectors
  summary: Line Styles collectors
  example: []
  syntax:
    content: >-
      [IsVisibleInDynamoLibrary(false)]

      public static class LineStyleCollectors
    content.vb: >-
      <IsVisibleInDynamoLibrary(False)>

      Public Module LineStyleCollectors
  inheritance:
  - System.Object
  inheritedMembers:
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ToString
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.GetHashCode
  attributes:
  - type: Autodesk.DesignScript.Runtime.IsVisibleInDynamoLibraryAttribute
    ctor: Autodesk.DesignScript.Runtime.IsVisibleInDynamoLibraryAttribute.#ctor(System.Boolean)
    arguments:
    - type: System.Boolean
      value: false
- uid: DynamoForRevitUtils.Services.Collectors.LineStyleCollectors.AllProjectionStyles(Autodesk.Revit.DB.Document)
  commentId: M:DynamoForRevitUtils.Services.Collectors.LineStyleCollectors.AllProjectionStyles(Autodesk.Revit.DB.Document)
  id: AllProjectionStyles(Autodesk.Revit.DB.Document)
  isExtensionMethod: true
  parent: DynamoForRevitUtils.Services.Collectors.LineStyleCollectors
  langs:
  - csharp
  - vb
  name: AllProjectionStyles(Document)
  nameWithType: LineStyleCollectors.AllProjectionStyles(Document)
  fullName: DynamoForRevitUtils.Services.Collectors.LineStyleCollectors.AllProjectionStyles(Autodesk.Revit.DB.Document)
  type: Method
  assemblies:
  - DynamoForRevitUtils
  namespace: DynamoForRevitUtils.Services.Collectors
  summary: Collects all Projection Line Styles from Document
  example: []
  syntax:
    content: public static List<GraphicsStyle> AllProjectionStyles(this Document doc)
    parameters:
    - id: doc
      type: Autodesk.Revit.DB.Document
      description: Revit Document to collect Line Styles
    return:
      type: System.Collections.Generic.List{Autodesk.Revit.DB.GraphicsStyle}
      description: Line Styles
    content.vb: Public Shared Function AllProjectionStyles(doc As Document) As List(Of GraphicsStyle)
  overload: DynamoForRevitUtils.Services.Collectors.LineStyleCollectors.AllProjectionStyles*
- uid: DynamoForRevitUtils.Services.Collectors.LineStyleCollectors.AllCutStyles(Autodesk.Revit.DB.Document)
  commentId: M:DynamoForRevitUtils.Services.Collectors.LineStyleCollectors.AllCutStyles(Autodesk.Revit.DB.Document)
  id: AllCutStyles(Autodesk.Revit.DB.Document)
  isExtensionMethod: true
  parent: DynamoForRevitUtils.Services.Collectors.LineStyleCollectors
  langs:
  - csharp
  - vb
  name: AllCutStyles(Document)
  nameWithType: LineStyleCollectors.AllCutStyles(Document)
  fullName: DynamoForRevitUtils.Services.Collectors.LineStyleCollectors.AllCutStyles(Autodesk.Revit.DB.Document)
  type: Method
  assemblies:
  - DynamoForRevitUtils
  namespace: DynamoForRevitUtils.Services.Collectors
  summary: Collects all Cut Line Styles from Document
  example: []
  syntax:
    content: public static List<GraphicsStyle> AllCutStyles(this Document doc)
    parameters:
    - id: doc
      type: Autodesk.Revit.DB.Document
      description: Revit Document to collect Line Styles
    return:
      type: System.Collections.Generic.List{Autodesk.Revit.DB.GraphicsStyle}
      description: Line Styles
    content.vb: Public Shared Function AllCutStyles(doc As Document) As List(Of GraphicsStyle)
  overload: DynamoForRevitUtils.Services.Collectors.LineStyleCollectors.AllCutStyles*
references:
- uid: DynamoForRevitUtils.Services.Collectors
  commentId: N:DynamoForRevitUtils.Services.Collectors
  isExternal: true
  href: DynamoForRevitUtils.html
  name: DynamoForRevitUtils.Services.Collectors
  nameWithType: DynamoForRevitUtils.Services.Collectors
  fullName: DynamoForRevitUtils.Services.Collectors
  spec.csharp:
  - uid: DynamoForRevitUtils
    name: DynamoForRevitUtils
    isExternal: true
    href: DynamoForRevitUtils.html
  - name: .
  - uid: DynamoForRevitUtils.Services
    name: Services
    isExternal: true
    href: DynamoForRevitUtils.Services.html
  - name: .
  - uid: DynamoForRevitUtils.Services.Collectors
    name: Collectors
    isExternal: true
    href: DynamoForRevitUtils.Services.Collectors.html
  spec.vb:
  - uid: DynamoForRevitUtils
    name: DynamoForRevitUtils
    isExternal: true
    href: DynamoForRevitUtils.html
  - name: .
  - uid: DynamoForRevitUtils.Services
    name: Services
    isExternal: true
    href: DynamoForRevitUtils.Services.html
  - name: .
  - uid: DynamoForRevitUtils.Services.Collectors
    name: Collectors
    isExternal: true
    href: DynamoForRevitUtils.Services.Collectors.html
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object
  name: object
  nameWithType: object
  fullName: object
  nameWithType.vb: Object
  fullName.vb: Object
  name.vb: Object
- uid: System.Object.GetType
  commentId: M:System.Object.GetType
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  name: GetType()
  nameWithType: object.GetType()
  fullName: object.GetType()
  nameWithType.vb: Object.GetType()
  fullName.vb: Object.GetType()
  spec.csharp:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
- uid: System.Object.MemberwiseClone
  commentId: M:System.Object.MemberwiseClone
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  name: MemberwiseClone()
  nameWithType: object.MemberwiseClone()
  fullName: object.MemberwiseClone()
  nameWithType.vb: Object.MemberwiseClone()
  fullName.vb: Object.MemberwiseClone()
  spec.csharp:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  - name: (
  - name: )
- uid: System.Object.ToString
  commentId: M:System.Object.ToString
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  name: ToString()
  nameWithType: object.ToString()
  fullName: object.ToString()
  nameWithType.vb: Object.ToString()
  fullName.vb: Object.ToString()
  spec.csharp:
  - uid: System.Object.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  - name: (
  - name: )
- uid: System.Object.Equals(System.Object)
  commentId: M:System.Object.Equals(System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  name: Equals(object)
  nameWithType: object.Equals(object)
  fullName: object.Equals(object)
  nameWithType.vb: Object.Equals(Object)
  fullName.vb: Object.Equals(Object)
  name.vb: Equals(Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.Equals(System.Object,System.Object)
  commentId: M:System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  name: Equals(object, object)
  nameWithType: object.Equals(object, object)
  fullName: object.Equals(object, object)
  nameWithType.vb: Object.Equals(Object, Object)
  fullName.vb: Object.Equals(Object, Object)
  name.vb: Equals(Object, Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  commentId: M:System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  name: ReferenceEquals(object, object)
  nameWithType: object.ReferenceEquals(object, object)
  fullName: object.ReferenceEquals(object, object)
  nameWithType.vb: Object.ReferenceEquals(Object, Object)
  fullName.vb: Object.ReferenceEquals(Object, Object)
  name.vb: ReferenceEquals(Object, Object)
  spec.csharp:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.GetHashCode
  commentId: M:System.Object.GetHashCode
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  name: GetHashCode()
  nameWithType: object.GetHashCode()
  fullName: object.GetHashCode()
  nameWithType.vb: Object.GetHashCode()
  fullName.vb: Object.GetHashCode()
  spec.csharp:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  - name: (
  - name: )
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: DynamoForRevitUtils.Services.Collectors.LineStyleCollectors.AllProjectionStyles*
  commentId: Overload:DynamoForRevitUtils.Services.Collectors.LineStyleCollectors.AllProjectionStyles
  isExternal: true
  href: DynamoForRevitUtils.Services.Collectors.LineStyleCollectors.html#DynamoForRevitUtils_Services_Collectors_LineStyleCollectors_AllProjectionStyles_Autodesk_Revit_DB_Document_
  name: AllProjectionStyles
  nameWithType: LineStyleCollectors.AllProjectionStyles
  fullName: DynamoForRevitUtils.Services.Collectors.LineStyleCollectors.AllProjectionStyles
- uid: Autodesk.Revit.DB.Document
  commentId: T:Autodesk.Revit.DB.Document
  parent: Autodesk.Revit.DB
  isExternal: true
  name: Document
  nameWithType: Document
  fullName: Autodesk.Revit.DB.Document
- uid: System.Collections.Generic.List{Autodesk.Revit.DB.GraphicsStyle}
  commentId: T:System.Collections.Generic.List{Autodesk.Revit.DB.GraphicsStyle}
  parent: System.Collections.Generic
  definition: System.Collections.Generic.List`1
  href: https://learn.microsoft.com/dotnet/api/system.collections.generic.list-1
  name: List<GraphicsStyle>
  nameWithType: List<GraphicsStyle>
  fullName: System.Collections.Generic.List<Autodesk.Revit.DB.GraphicsStyle>
  nameWithType.vb: List(Of GraphicsStyle)
  fullName.vb: System.Collections.Generic.List(Of Autodesk.Revit.DB.GraphicsStyle)
  name.vb: List(Of GraphicsStyle)
  spec.csharp:
  - uid: System.Collections.Generic.List`1
    name: List
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections.generic.list-1
  - name: <
  - uid: Autodesk.Revit.DB.GraphicsStyle
    name: GraphicsStyle
    isExternal: true
  - name: '>'
  spec.vb:
  - uid: System.Collections.Generic.List`1
    name: List
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections.generic.list-1
  - name: (
  - name: Of
  - name: " "
  - uid: Autodesk.Revit.DB.GraphicsStyle
    name: GraphicsStyle
    isExternal: true
  - name: )
- uid: Autodesk.Revit.DB
  commentId: N:Autodesk.Revit.DB
  isExternal: true
  name: Autodesk.Revit.DB
  nameWithType: Autodesk.Revit.DB
  fullName: Autodesk.Revit.DB
  spec.csharp:
  - uid: Autodesk
    name: Autodesk
    isExternal: true
  - name: .
  - uid: Autodesk.Revit
    name: Revit
    isExternal: true
  - name: .
  - uid: Autodesk.Revit.DB
    name: DB
    isExternal: true
  spec.vb:
  - uid: Autodesk
    name: Autodesk
    isExternal: true
  - name: .
  - uid: Autodesk.Revit
    name: Revit
    isExternal: true
  - name: .
  - uid: Autodesk.Revit.DB
    name: DB
    isExternal: true
- uid: System.Collections.Generic.List`1
  commentId: T:System.Collections.Generic.List`1
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.collections.generic.list-1
  name: List<T>
  nameWithType: List<T>
  fullName: System.Collections.Generic.List<T>
  nameWithType.vb: List(Of T)
  fullName.vb: System.Collections.Generic.List(Of T)
  name.vb: List(Of T)
  spec.csharp:
  - uid: System.Collections.Generic.List`1
    name: List
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections.generic.list-1
  - name: <
  - name: T
  - name: '>'
  spec.vb:
  - uid: System.Collections.Generic.List`1
    name: List
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections.generic.list-1
  - name: (
  - name: Of
  - name: " "
  - name: T
  - name: )
- uid: System.Collections.Generic
  commentId: N:System.Collections.Generic
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System.Collections.Generic
  nameWithType: System.Collections.Generic
  fullName: System.Collections.Generic
  spec.csharp:
  - uid: System
    name: System
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system
  - name: .
  - uid: System.Collections
    name: Collections
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections
  - name: .
  - uid: System.Collections.Generic
    name: Generic
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections.generic
  spec.vb:
  - uid: System
    name: System
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system
  - name: .
  - uid: System.Collections
    name: Collections
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections
  - name: .
  - uid: System.Collections.Generic
    name: Generic
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections.generic
- uid: DynamoForRevitUtils.Services.Collectors.LineStyleCollectors.AllCutStyles*
  commentId: Overload:DynamoForRevitUtils.Services.Collectors.LineStyleCollectors.AllCutStyles
  isExternal: true
  href: DynamoForRevitUtils.Services.Collectors.LineStyleCollectors.html#DynamoForRevitUtils_Services_Collectors_LineStyleCollectors_AllCutStyles_Autodesk_Revit_DB_Document_
  name: AllCutStyles
  nameWithType: LineStyleCollectors.AllCutStyles
  fullName: DynamoForRevitUtils.Services.Collectors.LineStyleCollectors.AllCutStyles
