### YamlMime:ManagedReference
items:
- uid: DynamoForRevitUtils.Enumerations.SelectionMethod
  commentId: T:DynamoForRevitUtils.Enumerations.SelectionMethod
  id: SelectionMethod
  parent: DynamoForRevitUtils.Enumerations
  children:
  - DynamoForRevitUtils.Enumerations.SelectionMethod.AllElements
  - DynamoForRevitUtils.Enumerations.SelectionMethod.AllElementsFromActiveView
  - DynamoForRevitUtils.Enumerations.SelectionMethod.Manual
  langs:
  - csharp
  - vb
  name: SelectionMethod
  nameWithType: SelectionMethod
  fullName: DynamoForRevitUtils.Enumerations.SelectionMethod
  type: Enum
  assemblies:
  - DynamoForRevitUtils
  namespace: DynamoForRevitUtils.Enumerations
  summary: Enumeration containing Selection Methods for Selection Nodes usage
  example: []
  syntax:
    content: public enum SelectionMethod
    content.vb: Public Enum SelectionMethod
  extensionMethods:
  - System.Object.DynamoForRevitUtils.Services.GenericServices.ObjectServices.TryCast``1
- uid: DynamoForRevitUtils.Enumerations.SelectionMethod.Manual
  commentId: F:DynamoForRevitUtils.Enumerations.SelectionMethod.Manual
  id: Manual
  parent: DynamoForRevitUtils.Enumerations.SelectionMethod
  langs:
  - csharp
  - vb
  name: Manual
  nameWithType: SelectionMethod.Manual
  fullName: DynamoForRevitUtils.Enumerations.SelectionMethod.Manual
  type: Field
  assemblies:
  - DynamoForRevitUtils
  namespace: DynamoForRevitUtils.Enumerations
  summary: Enable selection nodes to method PickObjects
  example: []
  syntax:
    content: Manual = 0
    return:
      type: DynamoForRevitUtils.Enumerations.SelectionMethod
- uid: DynamoForRevitUtils.Enumerations.SelectionMethod.AllElements
  commentId: F:DynamoForRevitUtils.Enumerations.SelectionMethod.AllElements
  id: AllElements
  parent: DynamoForRevitUtils.Enumerations.SelectionMethod
  langs:
  - csharp
  - vb
  name: AllElements
  nameWithType: SelectionMethod.AllElements
  fullName: DynamoForRevitUtils.Enumerations.SelectionMethod.AllElements
  type: Field
  assemblies:
  - DynamoForRevitUtils
  namespace: DynamoForRevitUtils.Enumerations
  summary: Make selection nodes returns all objects from model
  example: []
  syntax:
    content: AllElements = 1
    return:
      type: DynamoForRevitUtils.Enumerations.SelectionMethod
- uid: DynamoForRevitUtils.Enumerations.SelectionMethod.AllElementsFromActiveView
  commentId: F:DynamoForRevitUtils.Enumerations.SelectionMethod.AllElementsFromActiveView
  id: AllElementsFromActiveView
  parent: DynamoForRevitUtils.Enumerations.SelectionMethod
  langs:
  - csharp
  - vb
  name: AllElementsFromActiveView
  nameWithType: SelectionMethod.AllElementsFromActiveView
  fullName: DynamoForRevitUtils.Enumerations.SelectionMethod.AllElementsFromActiveView
  type: Field
  assemblies:
  - DynamoForRevitUtils
  namespace: DynamoForRevitUtils.Enumerations
  summary: Make selection nodes returns all objects from active view
  example: []
  syntax:
    content: AllElementsFromActiveView = 2
    return:
      type: DynamoForRevitUtils.Enumerations.SelectionMethod
references:
- uid: DynamoForRevitUtils.Enumerations
  commentId: N:DynamoForRevitUtils.Enumerations
  isExternal: true
  href: DynamoForRevitUtils.html
  name: DynamoForRevitUtils.Enumerations
  nameWithType: DynamoForRevitUtils.Enumerations
  fullName: DynamoForRevitUtils.Enumerations
  spec.csharp:
  - uid: DynamoForRevitUtils
    name: DynamoForRevitUtils
    isExternal: true
    href: DynamoForRevitUtils.html
  - name: .
  - uid: DynamoForRevitUtils.Enumerations
    name: Enumerations
    isExternal: true
    href: DynamoForRevitUtils.Enumerations.html
  spec.vb:
  - uid: DynamoForRevitUtils
    name: DynamoForRevitUtils
    isExternal: true
    href: DynamoForRevitUtils.html
  - name: .
  - uid: DynamoForRevitUtils.Enumerations
    name: Enumerations
    isExternal: true
    href: DynamoForRevitUtils.Enumerations.html
- uid: System.Object.DynamoForRevitUtils.Services.GenericServices.ObjectServices.TryCast``1
  commentId: M:DynamoForRevitUtils.Services.GenericServices.ObjectServices.TryCast``1(System.Object)
  parent: DynamoForRevitUtils.Services.GenericServices.ObjectServices
  definition: DynamoForRevitUtils.Services.GenericServices.ObjectServices.TryCast``1(System.Object)
  href: DynamoForRevitUtils.Services.GenericServices.ObjectServices.html#DynamoForRevitUtils_Services_GenericServices_ObjectServices_TryCast__1_System_Object_
  name: TryCast<T>(object)
  nameWithType: ObjectServices.TryCast<T>(object)
  fullName: DynamoForRevitUtils.Services.GenericServices.ObjectServices.TryCast<T>(object)
  nameWithType.vb: ObjectServices.TryCast(Of T)(Object)
  fullName.vb: DynamoForRevitUtils.Services.GenericServices.ObjectServices.TryCast(Of T)(Object)
  name.vb: TryCast(Of T)(Object)
  spec.csharp:
  - uid: DynamoForRevitUtils.Services.GenericServices.ObjectServices.TryCast``1(System.Object)
    name: TryCast
    isExternal: true
    href: DynamoForRevitUtils.Services.GenericServices.ObjectServices.html#DynamoForRevitUtils_Services_GenericServices_ObjectServices_TryCast__1_System_Object_
  - name: <
  - name: T
  - name: '>'
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: DynamoForRevitUtils.Services.GenericServices.ObjectServices.TryCast``1(System.Object)
    name: TryCast
    isExternal: true
    href: DynamoForRevitUtils.Services.GenericServices.ObjectServices.html#DynamoForRevitUtils_Services_GenericServices_ObjectServices_TryCast__1_System_Object_
  - name: (
  - name: Of
  - name: " "
  - name: T
  - name: )
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: DynamoForRevitUtils.Services.GenericServices.ObjectServices.TryCast``1(System.Object)
  commentId: M:DynamoForRevitUtils.Services.GenericServices.ObjectServices.TryCast``1(System.Object)
  isExternal: true
  href: DynamoForRevitUtils.Services.GenericServices.ObjectServices.html#DynamoForRevitUtils_Services_GenericServices_ObjectServices_TryCast__1_System_Object_
  name: TryCast<T>(object)
  nameWithType: ObjectServices.TryCast<T>(object)
  fullName: DynamoForRevitUtils.Services.GenericServices.ObjectServices.TryCast<T>(object)
  nameWithType.vb: ObjectServices.TryCast(Of T)(Object)
  fullName.vb: DynamoForRevitUtils.Services.GenericServices.ObjectServices.TryCast(Of T)(Object)
  name.vb: TryCast(Of T)(Object)
  spec.csharp:
  - uid: DynamoForRevitUtils.Services.GenericServices.ObjectServices.TryCast``1(System.Object)
    name: TryCast
    isExternal: true
    href: DynamoForRevitUtils.Services.GenericServices.ObjectServices.html#DynamoForRevitUtils_Services_GenericServices_ObjectServices_TryCast__1_System_Object_
  - name: <
  - name: T
  - name: '>'
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: DynamoForRevitUtils.Services.GenericServices.ObjectServices.TryCast``1(System.Object)
    name: TryCast
    isExternal: true
    href: DynamoForRevitUtils.Services.GenericServices.ObjectServices.html#DynamoForRevitUtils_Services_GenericServices_ObjectServices_TryCast__1_System_Object_
  - name: (
  - name: Of
  - name: " "
  - name: T
  - name: )
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: DynamoForRevitUtils.Services.GenericServices.ObjectServices
  commentId: T:DynamoForRevitUtils.Services.GenericServices.ObjectServices
  parent: DynamoForRevitUtils.Services.GenericServices
  isExternal: true
  href: DynamoForRevitUtils.Services.GenericServices.ObjectServices.html
  name: ObjectServices
  nameWithType: ObjectServices
  fullName: DynamoForRevitUtils.Services.GenericServices.ObjectServices
- uid: DynamoForRevitUtils.Services.GenericServices
  commentId: N:DynamoForRevitUtils.Services.GenericServices
  isExternal: true
  href: DynamoForRevitUtils.html
  name: DynamoForRevitUtils.Services.GenericServices
  nameWithType: DynamoForRevitUtils.Services.GenericServices
  fullName: DynamoForRevitUtils.Services.GenericServices
  spec.csharp:
  - uid: DynamoForRevitUtils
    name: DynamoForRevitUtils
    isExternal: true
    href: DynamoForRevitUtils.html
  - name: .
  - uid: DynamoForRevitUtils.Services
    name: Services
    isExternal: true
    href: DynamoForRevitUtils.Services.html
  - name: .
  - uid: DynamoForRevitUtils.Services.GenericServices
    name: GenericServices
    isExternal: true
    href: DynamoForRevitUtils.Services.GenericServices.html
  spec.vb:
  - uid: DynamoForRevitUtils
    name: DynamoForRevitUtils
    isExternal: true
    href: DynamoForRevitUtils.html
  - name: .
  - uid: DynamoForRevitUtils.Services
    name: Services
    isExternal: true
    href: DynamoForRevitUtils.Services.html
  - name: .
  - uid: DynamoForRevitUtils.Services.GenericServices
    name: GenericServices
    isExternal: true
    href: DynamoForRevitUtils.Services.GenericServices.html
- uid: DynamoForRevitUtils.Enumerations.SelectionMethod
  commentId: T:DynamoForRevitUtils.Enumerations.SelectionMethod
  parent: DynamoForRevitUtils.Enumerations
  isExternal: true
  href: DynamoForRevitUtils.Enumerations.SelectionMethod.html
  name: SelectionMethod
  nameWithType: SelectionMethod
  fullName: DynamoForRevitUtils.Enumerations.SelectionMethod
