### YamlMime:ManagedReference
items:
- uid: DynamoForRevitUtils.Services.MathServices.LinearAlgebraServices
  commentId: T:DynamoForRevitUtils.Services.MathServices.LinearAlgebraServices
  id: LinearAlgebraServices
  parent: DynamoForRevitUtils.Services.MathServices
  children:
  - DynamoForRevitUtils.Services.MathServices.LinearAlgebraServices.GetRelativeCoordinatesOfPoint(Autodesk.DesignScript.Geometry.Point,Autodesk.DesignScript.Geometry.CoordinateSystem)
  langs:
  - csharp
  - vb
  name: LinearAlgebraServices
  nameWithType: LinearAlgebraServices
  fullName: DynamoForRevitUtils.Services.MathServices.LinearAlgebraServices
  type: Class
  assemblies:
  - DynamoForRevitUtils
  namespace: DynamoForRevitUtils.Services.MathServices
  summary: Utils to perform linear algebra operations on Dynamo Geometry
  example: []
  syntax:
    content: >-
      [IsVisibleInDynamoLibrary(false)]

      public static class LinearAlgebraServices
    content.vb: >-
      <IsVisibleInDynamoLibrary(False)>

      Public Module LinearAlgebraServices
  inheritance:
  - System.Object
  inheritedMembers:
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ToString
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.GetHashCode
  attributes:
  - type: Autodesk.DesignScript.Runtime.IsVisibleInDynamoLibraryAttribute
    ctor: Autodesk.DesignScript.Runtime.IsVisibleInDynamoLibraryAttribute.#ctor(System.Boolean)
    arguments:
    - type: System.Boolean
      value: false
- uid: DynamoForRevitUtils.Services.MathServices.LinearAlgebraServices.GetRelativeCoordinatesOfPoint(Autodesk.DesignScript.Geometry.Point,Autodesk.DesignScript.Geometry.CoordinateSystem)
  commentId: M:DynamoForRevitUtils.Services.MathServices.LinearAlgebraServices.GetRelativeCoordinatesOfPoint(Autodesk.DesignScript.Geometry.Point,Autodesk.DesignScript.Geometry.CoordinateSystem)
  id: GetRelativeCoordinatesOfPoint(Autodesk.DesignScript.Geometry.Point,Autodesk.DesignScript.Geometry.CoordinateSystem)
  parent: DynamoForRevitUtils.Services.MathServices.LinearAlgebraServices
  langs:
  - csharp
  - vb
  name: GetRelativeCoordinatesOfPoint(Point, CoordinateSystem)
  nameWithType: LinearAlgebraServices.GetRelativeCoordinatesOfPoint(Point, CoordinateSystem)
  fullName: DynamoForRevitUtils.Services.MathServices.LinearAlgebraServices.GetRelativeCoordinatesOfPoint(Autodesk.DesignScript.Geometry.Point, Autodesk.DesignScript.Geometry.CoordinateSystem)
  type: Method
  assemblies:
  - DynamoForRevitUtils
  namespace: DynamoForRevitUtils.Services.MathServices
  summary: Get the coordinates of a point relative to a Coordinate System
  example: []
  syntax:
    content: public static (double X, double Y, double Z) GetRelativeCoordinatesOfPoint(Point point, CoordinateSystem cs)
    parameters:
    - id: point
      type: Autodesk.DesignScript.Geometry.Point
      description: Point to get the relative coordinates
    - id: cs
      type: Autodesk.DesignScript.Geometry.CoordinateSystem
      description: Coordinate System to get the relative coordinates
    return:
      type: System.ValueTuple{System.Double,System.Double,System.Double}
      description: Tuple with the relative coordinates of the point
    content.vb: Public Shared Function GetRelativeCoordinatesOfPoint(point As Point, cs As CoordinateSystem) As (X As Double, Y As Double, Z As Double)
  overload: DynamoForRevitUtils.Services.MathServices.LinearAlgebraServices.GetRelativeCoordinatesOfPoint*
references:
- uid: DynamoForRevitUtils.Services.MathServices
  commentId: N:DynamoForRevitUtils.Services.MathServices
  isExternal: true
  href: DynamoForRevitUtils.html
  name: DynamoForRevitUtils.Services.MathServices
  nameWithType: DynamoForRevitUtils.Services.MathServices
  fullName: DynamoForRevitUtils.Services.MathServices
  spec.csharp:
  - uid: DynamoForRevitUtils
    name: DynamoForRevitUtils
    isExternal: true
    href: DynamoForRevitUtils.html
  - name: .
  - uid: DynamoForRevitUtils.Services
    name: Services
    isExternal: true
    href: DynamoForRevitUtils.Services.html
  - name: .
  - uid: DynamoForRevitUtils.Services.MathServices
    name: MathServices
    isExternal: true
    href: DynamoForRevitUtils.Services.MathServices.html
  spec.vb:
  - uid: DynamoForRevitUtils
    name: DynamoForRevitUtils
    isExternal: true
    href: DynamoForRevitUtils.html
  - name: .
  - uid: DynamoForRevitUtils.Services
    name: Services
    isExternal: true
    href: DynamoForRevitUtils.Services.html
  - name: .
  - uid: DynamoForRevitUtils.Services.MathServices
    name: MathServices
    isExternal: true
    href: DynamoForRevitUtils.Services.MathServices.html
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object
  name: object
  nameWithType: object
  fullName: object
  nameWithType.vb: Object
  fullName.vb: Object
  name.vb: Object
- uid: System.Object.GetType
  commentId: M:System.Object.GetType
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  name: GetType()
  nameWithType: object.GetType()
  fullName: object.GetType()
  nameWithType.vb: Object.GetType()
  fullName.vb: Object.GetType()
  spec.csharp:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
- uid: System.Object.MemberwiseClone
  commentId: M:System.Object.MemberwiseClone
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  name: MemberwiseClone()
  nameWithType: object.MemberwiseClone()
  fullName: object.MemberwiseClone()
  nameWithType.vb: Object.MemberwiseClone()
  fullName.vb: Object.MemberwiseClone()
  spec.csharp:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  - name: (
  - name: )
- uid: System.Object.ToString
  commentId: M:System.Object.ToString
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  name: ToString()
  nameWithType: object.ToString()
  fullName: object.ToString()
  nameWithType.vb: Object.ToString()
  fullName.vb: Object.ToString()
  spec.csharp:
  - uid: System.Object.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  - name: (
  - name: )
- uid: System.Object.Equals(System.Object)
  commentId: M:System.Object.Equals(System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  name: Equals(object)
  nameWithType: object.Equals(object)
  fullName: object.Equals(object)
  nameWithType.vb: Object.Equals(Object)
  fullName.vb: Object.Equals(Object)
  name.vb: Equals(Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.Equals(System.Object,System.Object)
  commentId: M:System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  name: Equals(object, object)
  nameWithType: object.Equals(object, object)
  fullName: object.Equals(object, object)
  nameWithType.vb: Object.Equals(Object, Object)
  fullName.vb: Object.Equals(Object, Object)
  name.vb: Equals(Object, Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  commentId: M:System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  name: ReferenceEquals(object, object)
  nameWithType: object.ReferenceEquals(object, object)
  fullName: object.ReferenceEquals(object, object)
  nameWithType.vb: Object.ReferenceEquals(Object, Object)
  fullName.vb: Object.ReferenceEquals(Object, Object)
  name.vb: ReferenceEquals(Object, Object)
  spec.csharp:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.GetHashCode
  commentId: M:System.Object.GetHashCode
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  name: GetHashCode()
  nameWithType: object.GetHashCode()
  fullName: object.GetHashCode()
  nameWithType.vb: Object.GetHashCode()
  fullName.vb: Object.GetHashCode()
  spec.csharp:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  - name: (
  - name: )
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: DynamoForRevitUtils.Services.MathServices.LinearAlgebraServices.GetRelativeCoordinatesOfPoint*
  commentId: Overload:DynamoForRevitUtils.Services.MathServices.LinearAlgebraServices.GetRelativeCoordinatesOfPoint
  isExternal: true
  href: DynamoForRevitUtils.Services.MathServices.LinearAlgebraServices.html#DynamoForRevitUtils_Services_MathServices_LinearAlgebraServices_GetRelativeCoordinatesOfPoint_Autodesk_DesignScript_Geometry_Point_Autodesk_DesignScript_Geometry_CoordinateSystem_
  name: GetRelativeCoordinatesOfPoint
  nameWithType: LinearAlgebraServices.GetRelativeCoordinatesOfPoint
  fullName: DynamoForRevitUtils.Services.MathServices.LinearAlgebraServices.GetRelativeCoordinatesOfPoint
- uid: Autodesk.DesignScript.Geometry.Point
  commentId: T:Autodesk.DesignScript.Geometry.Point
  parent: Autodesk.DesignScript.Geometry
  isExternal: true
  name: Point
  nameWithType: Point
  fullName: Autodesk.DesignScript.Geometry.Point
- uid: Autodesk.DesignScript.Geometry.CoordinateSystem
  commentId: T:Autodesk.DesignScript.Geometry.CoordinateSystem
  parent: Autodesk.DesignScript.Geometry
  isExternal: true
  name: CoordinateSystem
  nameWithType: CoordinateSystem
  fullName: Autodesk.DesignScript.Geometry.CoordinateSystem
- uid: System.ValueTuple{System.Double,System.Double,System.Double}
  commentId: T:System.ValueTuple{System.Double,System.Double,System.Double}
  parent: System
  definition: System.ValueTuple`3
  href: https://learn.microsoft.com/dotnet/api/system.double
  name: (double X, double Y, double Z)
  nameWithType: (double X, double Y, double Z)
  fullName: (double X, double Y, double Z)
  nameWithType.vb: (X As Double, Y As Double, Z As Double)
  fullName.vb: (X As Double, Y As Double, Z As Double)
  name.vb: (X As Double, Y As Double, Z As Double)
  spec.csharp:
  - name: (
  - uid: System.Double
    name: double
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.double
  - name: " "
  - uid: System.ValueTuple{System.Double,System.Double,System.Double}.X
    name: X
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.valuetuple-system.double,system.double,system.double-.x
  - name: ','
  - name: " "
  - uid: System.Double
    name: double
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.double
  - name: " "
  - uid: System.ValueTuple{System.Double,System.Double,System.Double}.Y
    name: Y
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.valuetuple-system.double,system.double,system.double-.y
  - name: ','
  - name: " "
  - uid: System.Double
    name: double
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.double
  - name: " "
  - uid: System.ValueTuple{System.Double,System.Double,System.Double}.Z
    name: Z
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.valuetuple-system.double,system.double,system.double-.z
  - name: )
  spec.vb:
  - name: (
  - uid: System.ValueTuple{System.Double,System.Double,System.Double}.X
    name: X
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.valuetuple-system.double,system.double,system.double-.x
  - name: " "
  - name: As
  - name: " "
  - uid: System.Double
    name: Double
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.double
  - name: ','
  - name: " "
  - uid: System.ValueTuple{System.Double,System.Double,System.Double}.Y
    name: Y
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.valuetuple-system.double,system.double,system.double-.y
  - name: " "
  - name: As
  - name: " "
  - uid: System.Double
    name: Double
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.double
  - name: ','
  - name: " "
  - uid: System.ValueTuple{System.Double,System.Double,System.Double}.Z
    name: Z
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.valuetuple-system.double,system.double,system.double-.z
  - name: " "
  - name: As
  - name: " "
  - uid: System.Double
    name: Double
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.double
  - name: )
- uid: Autodesk.DesignScript.Geometry
  commentId: N:Autodesk.DesignScript.Geometry
  isExternal: true
  name: Autodesk.DesignScript.Geometry
  nameWithType: Autodesk.DesignScript.Geometry
  fullName: Autodesk.DesignScript.Geometry
  spec.csharp:
  - uid: Autodesk
    name: Autodesk
    isExternal: true
  - name: .
  - uid: Autodesk.DesignScript
    name: DesignScript
    isExternal: true
  - name: .
  - uid: Autodesk.DesignScript.Geometry
    name: Geometry
    isExternal: true
  spec.vb:
  - uid: Autodesk
    name: Autodesk
    isExternal: true
  - name: .
  - uid: Autodesk.DesignScript
    name: DesignScript
    isExternal: true
  - name: .
  - uid: Autodesk.DesignScript.Geometry
    name: Geometry
    isExternal: true
- uid: System.ValueTuple`3
  commentId: T:System.ValueTuple`3
  name: (T1, T2, T3)
  nameWithType: (T1, T2, T3)
  fullName: (T1, T2, T3)
  spec.csharp:
  - name: (
  - name: T1
  - name: ','
  - name: " "
  - name: T2
  - name: ','
  - name: " "
  - name: T3
  - name: )
  spec.vb:
  - name: (
  - name: T1
  - name: ','
  - name: " "
  - name: T2
  - name: ','
  - name: " "
  - name: T3
  - name: )
