### YamlMime:ManagedReference
items:
- uid: DynamoForRevitUtils.Enumerations.RoofLineType
  commentId: T:DynamoForRevitUtils.Enumerations.RoofLineType
  id: RoofLineType
  parent: DynamoForRevitUtils.Enumerations
  children:
  - DynamoForRevitUtils.Enumerations.RoofLineType.Eave
  - DynamoForRevitUtils.Enumerations.RoofLineType.Hip
  - DynamoForRevitUtils.Enumerations.RoofLineType.Ridge
  - DynamoForRevitUtils.Enumerations.RoofLineType.Undefined
  - DynamoForRevitUtils.Enumerations.RoofLineType.Valley
  langs:
  - csharp
  - vb
  name: RoofLineType
  nameWithType: RoofLineType
  fullName: DynamoForRevitUtils.Enumerations.RoofLineType
  type: Enum
  assemblies:
  - DynamoForRevitUtils
  namespace: DynamoForRevitUtils.Enumerations
  summary: Enum that defines Roof Line Types. Used in Roof Tiles Generator
  example: []
  syntax:
    content: public enum RoofLineType
    content.vb: Public Enum RoofLineType
  extensionMethods:
  - System.Object.DynamoForRevitUtils.Services.GenericServices.ObjectServices.TryCast``1
- uid: DynamoForRevitUtils.Enumerations.RoofLineType.Hip
  commentId: F:DynamoForRevitUtils.Enumerations.RoofLineType.Hip
  id: Hip
  parent: DynamoForRevitUtils.Enumerations.RoofLineType
  langs:
  - csharp
  - vb
  name: Hip
  nameWithType: RoofLineType.Hip
  fullName: DynamoForRevitUtils.Enumerations.RoofLineType.Hip
  type: Field
  assemblies:
  - DynamoForRevitUtils
  namespace: DynamoForRevitUtils.Enumerations
  summary: Enum member for Hip in the RoofLineType enum. Represents a hip roof line type.
  example: []
  syntax:
    content: Hip = 0
    return:
      type: DynamoForRevitUtils.Enumerations.RoofLineType
- uid: DynamoForRevitUtils.Enumerations.RoofLineType.Ridge
  commentId: F:DynamoForRevitUtils.Enumerations.RoofLineType.Ridge
  id: Ridge
  parent: DynamoForRevitUtils.Enumerations.RoofLineType
  langs:
  - csharp
  - vb
  name: Ridge
  nameWithType: RoofLineType.Ridge
  fullName: DynamoForRevitUtils.Enumerations.RoofLineType.Ridge
  type: Field
  assemblies:
  - DynamoForRevitUtils
  namespace: DynamoForRevitUtils.Enumerations
  summary: Enum member that represents the ridge roof line type.
  example: []
  syntax:
    content: Ridge = 1
    return:
      type: DynamoForRevitUtils.Enumerations.RoofLineType
- uid: DynamoForRevitUtils.Enumerations.RoofLineType.Valley
  commentId: F:DynamoForRevitUtils.Enumerations.RoofLineType.Valley
  id: Valley
  parent: DynamoForRevitUtils.Enumerations.RoofLineType
  langs:
  - csharp
  - vb
  name: Valley
  nameWithType: RoofLineType.Valley
  fullName: DynamoForRevitUtils.Enumerations.RoofLineType.Valley
  type: Field
  assemblies:
  - DynamoForRevitUtils
  namespace: DynamoForRevitUtils.Enumerations
  summary: Enum that defines Roof Line Types.
  example: []
  syntax:
    content: Valley = 2
    return:
      type: DynamoForRevitUtils.Enumerations.RoofLineType
- uid: DynamoForRevitUtils.Enumerations.RoofLineType.Eave
  commentId: F:DynamoForRevitUtils.Enumerations.RoofLineType.Eave
  id: Eave
  parent: DynamoForRevitUtils.Enumerations.RoofLineType
  langs:
  - csharp
  - vb
  name: Eave
  nameWithType: RoofLineType.Eave
  fullName: DynamoForRevitUtils.Enumerations.RoofLineType.Eave
  type: Field
  assemblies:
  - DynamoForRevitUtils
  namespace: DynamoForRevitUtils.Enumerations
  summary: The Eave represents an enum member of the RoofLineType enum.
  example: []
  syntax:
    content: Eave = 3
    return:
      type: DynamoForRevitUtils.Enumerations.RoofLineType
- uid: DynamoForRevitUtils.Enumerations.RoofLineType.Undefined
  commentId: F:DynamoForRevitUtils.Enumerations.RoofLineType.Undefined
  id: Undefined
  parent: DynamoForRevitUtils.Enumerations.RoofLineType
  langs:
  - csharp
  - vb
  name: Undefined
  nameWithType: RoofLineType.Undefined
  fullName: DynamoForRevitUtils.Enumerations.RoofLineType.Undefined
  type: Field
  assemblies:
  - DynamoForRevitUtils
  namespace: DynamoForRevitUtils.Enumerations
  summary: Represents an undefined roof line type.
  remarks: This value is used when the roof line type is not specified or cannot be determined.
  example: []
  syntax:
    content: Undefined = 4
    return:
      type: DynamoForRevitUtils.Enumerations.RoofLineType
references:
- uid: DynamoForRevitUtils.Enumerations
  commentId: N:DynamoForRevitUtils.Enumerations
  isExternal: true
  href: DynamoForRevitUtils.html
  name: DynamoForRevitUtils.Enumerations
  nameWithType: DynamoForRevitUtils.Enumerations
  fullName: DynamoForRevitUtils.Enumerations
  spec.csharp:
  - uid: DynamoForRevitUtils
    name: DynamoForRevitUtils
    isExternal: true
    href: DynamoForRevitUtils.html
  - name: .
  - uid: DynamoForRevitUtils.Enumerations
    name: Enumerations
    isExternal: true
    href: DynamoForRevitUtils.Enumerations.html
  spec.vb:
  - uid: DynamoForRevitUtils
    name: DynamoForRevitUtils
    isExternal: true
    href: DynamoForRevitUtils.html
  - name: .
  - uid: DynamoForRevitUtils.Enumerations
    name: Enumerations
    isExternal: true
    href: DynamoForRevitUtils.Enumerations.html
- uid: System.Object.DynamoForRevitUtils.Services.GenericServices.ObjectServices.TryCast``1
  commentId: M:DynamoForRevitUtils.Services.GenericServices.ObjectServices.TryCast``1(System.Object)
  parent: DynamoForRevitUtils.Services.GenericServices.ObjectServices
  definition: DynamoForRevitUtils.Services.GenericServices.ObjectServices.TryCast``1(System.Object)
  href: DynamoForRevitUtils.Services.GenericServices.ObjectServices.html#DynamoForRevitUtils_Services_GenericServices_ObjectServices_TryCast__1_System_Object_
  name: TryCast<T>(object)
  nameWithType: ObjectServices.TryCast<T>(object)
  fullName: DynamoForRevitUtils.Services.GenericServices.ObjectServices.TryCast<T>(object)
  nameWithType.vb: ObjectServices.TryCast(Of T)(Object)
  fullName.vb: DynamoForRevitUtils.Services.GenericServices.ObjectServices.TryCast(Of T)(Object)
  name.vb: TryCast(Of T)(Object)
  spec.csharp:
  - uid: DynamoForRevitUtils.Services.GenericServices.ObjectServices.TryCast``1(System.Object)
    name: TryCast
    isExternal: true
    href: DynamoForRevitUtils.Services.GenericServices.ObjectServices.html#DynamoForRevitUtils_Services_GenericServices_ObjectServices_TryCast__1_System_Object_
  - name: <
  - name: T
  - name: '>'
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: DynamoForRevitUtils.Services.GenericServices.ObjectServices.TryCast``1(System.Object)
    name: TryCast
    isExternal: true
    href: DynamoForRevitUtils.Services.GenericServices.ObjectServices.html#DynamoForRevitUtils_Services_GenericServices_ObjectServices_TryCast__1_System_Object_
  - name: (
  - name: Of
  - name: " "
  - name: T
  - name: )
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: DynamoForRevitUtils.Services.GenericServices.ObjectServices.TryCast``1(System.Object)
  commentId: M:DynamoForRevitUtils.Services.GenericServices.ObjectServices.TryCast``1(System.Object)
  isExternal: true
  href: DynamoForRevitUtils.Services.GenericServices.ObjectServices.html#DynamoForRevitUtils_Services_GenericServices_ObjectServices_TryCast__1_System_Object_
  name: TryCast<T>(object)
  nameWithType: ObjectServices.TryCast<T>(object)
  fullName: DynamoForRevitUtils.Services.GenericServices.ObjectServices.TryCast<T>(object)
  nameWithType.vb: ObjectServices.TryCast(Of T)(Object)
  fullName.vb: DynamoForRevitUtils.Services.GenericServices.ObjectServices.TryCast(Of T)(Object)
  name.vb: TryCast(Of T)(Object)
  spec.csharp:
  - uid: DynamoForRevitUtils.Services.GenericServices.ObjectServices.TryCast``1(System.Object)
    name: TryCast
    isExternal: true
    href: DynamoForRevitUtils.Services.GenericServices.ObjectServices.html#DynamoForRevitUtils_Services_GenericServices_ObjectServices_TryCast__1_System_Object_
  - name: <
  - name: T
  - name: '>'
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: DynamoForRevitUtils.Services.GenericServices.ObjectServices.TryCast``1(System.Object)
    name: TryCast
    isExternal: true
    href: DynamoForRevitUtils.Services.GenericServices.ObjectServices.html#DynamoForRevitUtils_Services_GenericServices_ObjectServices_TryCast__1_System_Object_
  - name: (
  - name: Of
  - name: " "
  - name: T
  - name: )
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: DynamoForRevitUtils.Services.GenericServices.ObjectServices
  commentId: T:DynamoForRevitUtils.Services.GenericServices.ObjectServices
  parent: DynamoForRevitUtils.Services.GenericServices
  isExternal: true
  href: DynamoForRevitUtils.Services.GenericServices.ObjectServices.html
  name: ObjectServices
  nameWithType: ObjectServices
  fullName: DynamoForRevitUtils.Services.GenericServices.ObjectServices
- uid: DynamoForRevitUtils.Services.GenericServices
  commentId: N:DynamoForRevitUtils.Services.GenericServices
  isExternal: true
  href: DynamoForRevitUtils.html
  name: DynamoForRevitUtils.Services.GenericServices
  nameWithType: DynamoForRevitUtils.Services.GenericServices
  fullName: DynamoForRevitUtils.Services.GenericServices
  spec.csharp:
  - uid: DynamoForRevitUtils
    name: DynamoForRevitUtils
    isExternal: true
    href: DynamoForRevitUtils.html
  - name: .
  - uid: DynamoForRevitUtils.Services
    name: Services
    isExternal: true
    href: DynamoForRevitUtils.Services.html
  - name: .
  - uid: DynamoForRevitUtils.Services.GenericServices
    name: GenericServices
    isExternal: true
    href: DynamoForRevitUtils.Services.GenericServices.html
  spec.vb:
  - uid: DynamoForRevitUtils
    name: DynamoForRevitUtils
    isExternal: true
    href: DynamoForRevitUtils.html
  - name: .
  - uid: DynamoForRevitUtils.Services
    name: Services
    isExternal: true
    href: DynamoForRevitUtils.Services.html
  - name: .
  - uid: DynamoForRevitUtils.Services.GenericServices
    name: GenericServices
    isExternal: true
    href: DynamoForRevitUtils.Services.GenericServices.html
- uid: DynamoForRevitUtils.Enumerations.RoofLineType
  commentId: T:DynamoForRevitUtils.Enumerations.RoofLineType
  parent: DynamoForRevitUtils.Enumerations
  isExternal: true
  href: DynamoForRevitUtils.Enumerations.RoofLineType.html
  name: RoofLineType
  nameWithType: RoofLineType
  fullName: DynamoForRevitUtils.Enumerations.RoofLineType
