### YamlMime:ManagedReference
items:
- uid: DynamoForRevitUtils.Entities.ParametersHandlers
  commentId: N:DynamoForRevitUtils.Entities.ParametersHandlers
  id: DynamoForRevitUtils.Entities.ParametersHandlers
  children:
  - DynamoForRevitUtils.Entities.ParametersHandlers.AccessParameterInfo
  - DynamoForRevitUtils.Entities.ParametersHandlers.AccessParameterOptions
  - DynamoForRevitUtils.Entities.ParametersHandlers.ElementParameter
  - DynamoForRevitUtils.Entities.ParametersHandlers.ElementParameterAccessor`1
  - DynamoForRevitUtils.Entities.ParametersHandlers.ElementWrapperParameters`1
  - DynamoForRevitUtils.Entities.ParametersHandlers.IElementWrapperParameters
  - DynamoForRevitUtils.Entities.ParametersHandlers.WrapperPropertyParameterBinding
  langs:
  - csharp
  - vb
  name: DynamoForRevitUtils.Entities.ParametersHandlers
  nameWithType: DynamoForRevitUtils.Entities.ParametersHandlers
  fullName: DynamoForRevitUtils.Entities.ParametersHandlers
  type: Namespace
  assemblies:
  - DynamoForRevitUtils
references:
- uid: DynamoForRevitUtils.Entities.ParametersHandlers.AccessParameterInfo
  commentId: T:DynamoForRevitUtils.Entities.ParametersHandlers.AccessParameterInfo
  parent: DynamoForRevitUtils.Entities.ParametersHandlers
  isExternal: true
  href: DynamoForRevitUtils.Entities.ParametersHandlers.AccessParameterInfo.html
  name: AccessParameterInfo
  nameWithType: AccessParameterInfo
  fullName: DynamoForRevitUtils.Entities.ParametersHandlers.AccessParameterInfo
- uid: DynamoForRevitUtils.Entities.ParametersHandlers.AccessParameterOptions
  commentId: T:DynamoForRevitUtils.Entities.ParametersHandlers.AccessParameterOptions
  parent: DynamoForRevitUtils.Entities.ParametersHandlers
  isExternal: true
  href: DynamoForRevitUtils.Entities.ParametersHandlers.AccessParameterOptions.html
  name: AccessParameterOptions
  nameWithType: AccessParameterOptions
  fullName: DynamoForRevitUtils.Entities.ParametersHandlers.AccessParameterOptions
- uid: DynamoForRevitUtils.Entities.ParametersHandlers.ElementParameter
  commentId: T:DynamoForRevitUtils.Entities.ParametersHandlers.ElementParameter
  parent: DynamoForRevitUtils.Entities.ParametersHandlers
  isExternal: true
  href: DynamoForRevitUtils.Entities.ParametersHandlers.ElementParameter.html
  name: ElementParameter
  nameWithType: ElementParameter
  fullName: DynamoForRevitUtils.Entities.ParametersHandlers.ElementParameter
- uid: DynamoForRevitUtils.Entities.ParametersHandlers.ElementParameterAccessor`1
  commentId: T:DynamoForRevitUtils.Entities.ParametersHandlers.ElementParameterAccessor`1
  isExternal: true
  href: DynamoForRevitUtils.Entities.ParametersHandlers.ElementParameterAccessor-1.html
  name: ElementParameterAccessor<TWrapperParams>
  nameWithType: ElementParameterAccessor<TWrapperParams>
  fullName: DynamoForRevitUtils.Entities.ParametersHandlers.ElementParameterAccessor<TWrapperParams>
  nameWithType.vb: ElementParameterAccessor(Of TWrapperParams)
  fullName.vb: DynamoForRevitUtils.Entities.ParametersHandlers.ElementParameterAccessor(Of TWrapperParams)
  name.vb: ElementParameterAccessor(Of TWrapperParams)
  spec.csharp:
  - uid: DynamoForRevitUtils.Entities.ParametersHandlers.ElementParameterAccessor`1
    name: ElementParameterAccessor
    isExternal: true
    href: DynamoForRevitUtils.Entities.ParametersHandlers.ElementParameterAccessor-1.html
  - name: <
  - name: TWrapperParams
  - name: '>'
  spec.vb:
  - uid: DynamoForRevitUtils.Entities.ParametersHandlers.ElementParameterAccessor`1
    name: ElementParameterAccessor
    isExternal: true
    href: DynamoForRevitUtils.Entities.ParametersHandlers.ElementParameterAccessor-1.html
  - name: (
  - name: Of
  - name: " "
  - name: TWrapperParams
  - name: )
- uid: DynamoForRevitUtils.Entities.ParametersHandlers.ElementWrapperParameters`1
  commentId: T:DynamoForRevitUtils.Entities.ParametersHandlers.ElementWrapperParameters`1
  isExternal: true
  href: DynamoForRevitUtils.Entities.ParametersHandlers.ElementWrapperParameters-1.html
  name: ElementWrapperParameters<T>
  nameWithType: ElementWrapperParameters<T>
  fullName: DynamoForRevitUtils.Entities.ParametersHandlers.ElementWrapperParameters<T>
  nameWithType.vb: ElementWrapperParameters(Of T)
  fullName.vb: DynamoForRevitUtils.Entities.ParametersHandlers.ElementWrapperParameters(Of T)
  name.vb: ElementWrapperParameters(Of T)
  spec.csharp:
  - uid: DynamoForRevitUtils.Entities.ParametersHandlers.ElementWrapperParameters`1
    name: ElementWrapperParameters
    isExternal: true
    href: DynamoForRevitUtils.Entities.ParametersHandlers.ElementWrapperParameters-1.html
  - name: <
  - name: T
  - name: '>'
  spec.vb:
  - uid: DynamoForRevitUtils.Entities.ParametersHandlers.ElementWrapperParameters`1
    name: ElementWrapperParameters
    isExternal: true
    href: DynamoForRevitUtils.Entities.ParametersHandlers.ElementWrapperParameters-1.html
  - name: (
  - name: Of
  - name: " "
  - name: T
  - name: )
- uid: DynamoForRevitUtils.Entities.ParametersHandlers.IElementWrapperParameters
  commentId: T:DynamoForRevitUtils.Entities.ParametersHandlers.IElementWrapperParameters
  parent: DynamoForRevitUtils.Entities.ParametersHandlers
  isExternal: true
  href: DynamoForRevitUtils.Entities.ParametersHandlers.IElementWrapperParameters.html
  name: IElementWrapperParameters
  nameWithType: IElementWrapperParameters
  fullName: DynamoForRevitUtils.Entities.ParametersHandlers.IElementWrapperParameters
- uid: DynamoForRevitUtils.Entities.ParametersHandlers.WrapperPropertyParameterBinding
  commentId: T:DynamoForRevitUtils.Entities.ParametersHandlers.WrapperPropertyParameterBinding
  isExternal: true
  href: DynamoForRevitUtils.Entities.ParametersHandlers.WrapperPropertyParameterBinding.html
  name: WrapperPropertyParameterBinding
  nameWithType: WrapperPropertyParameterBinding
  fullName: DynamoForRevitUtils.Entities.ParametersHandlers.WrapperPropertyParameterBinding
- uid: DynamoForRevitUtils.Entities.ParametersHandlers
  commentId: N:DynamoForRevitUtils.Entities.ParametersHandlers
  isExternal: true
  href: DynamoForRevitUtils.html
  name: DynamoForRevitUtils.Entities.ParametersHandlers
  nameWithType: DynamoForRevitUtils.Entities.ParametersHandlers
  fullName: DynamoForRevitUtils.Entities.ParametersHandlers
  spec.csharp:
  - uid: DynamoForRevitUtils
    name: DynamoForRevitUtils
    isExternal: true
    href: DynamoForRevitUtils.html
  - name: .
  - uid: DynamoForRevitUtils.Entities
    name: Entities
    isExternal: true
    href: DynamoForRevitUtils.Entities.html
  - name: .
  - uid: DynamoForRevitUtils.Entities.ParametersHandlers
    name: ParametersHandlers
    isExternal: true
    href: DynamoForRevitUtils.Entities.ParametersHandlers.html
  spec.vb:
  - uid: DynamoForRevitUtils
    name: DynamoForRevitUtils
    isExternal: true
    href: DynamoForRevitUtils.html
  - name: .
  - uid: DynamoForRevitUtils.Entities
    name: Entities
    isExternal: true
    href: DynamoForRevitUtils.Entities.html
  - name: .
  - uid: DynamoForRevitUtils.Entities.ParametersHandlers
    name: ParametersHandlers
    isExternal: true
    href: DynamoForRevitUtils.Entities.ParametersHandlers.html
