### YamlMime:ManagedReference
items:
- uid: DynamoForRevitNodeModels.FunctionNodes
  commentId: N:DynamoForRevitNodeModels.FunctionNodes
  id: DynamoForRevitNodeModels.FunctionNodes
  children:
  - DynamoForRevitNodeModels.FunctionNodes.BoundingBoxViewer
  - DynamoForRevitNodeModels.FunctionNodes.BuiltInCategoryToDynamoCategory
  - DynamoForRevitNodeModels.FunctionNodes.BuiltInToUIName
  - DynamoForRevitNodeModels.FunctionNodes.CSVRead
  - DynamoForRevitNodeModels.FunctionNodes.CSVWrite
  - DynamoForRevitNodeModels.FunctionNodes.CoordinateSystemViewer
  - DynamoForRevitNodeModels.FunctionNodes.ElementParameterCreateByBuiltInParameter
  - DynamoForRevitNodeModels.FunctionNodes.ElementParameterCreateByName
  - DynamoForRevitNodeModels.FunctionNodes.ElementParameterDataType
  - DynamoForRevitNodeModels.FunctionNodes.ElementParameterKind
  - DynamoForRevitNodeModels.FunctionNodes.ElementParameterName
  - DynamoForRevitNodeModels.FunctionNodes.ElementParameterValue
  - DynamoForRevitNodeModels.FunctionNodes.GetSelectionResultsData
  - DynamoForRevitNodeModels.FunctionNodes.MultiReturnNodeModelBase
  - DynamoForRevitNodeModels.FunctionNodes.SelectionBySelectionMethodAndCategories
  - DynamoForRevitNodeModels.FunctionNodes.SelectionBySelectionMethodAndCategory
  - DynamoForRevitNodeModels.FunctionNodes.StandardNodeModelBase
  - DynamoForRevitNodeModels.FunctionNodes.StandardNodeModelBaseByResources
  - DynamoForRevitNodeModels.FunctionNodes.StringFilterByRegex
  - DynamoForRevitNodeModels.FunctionNodes.TopographyGetSurfaces
  - DynamoForRevitNodeModels.FunctionNodes.VectorViewer
  - DynamoForRevitNodeModels.FunctionNodes.ViewCollector
  langs:
  - csharp
  - vb
  name: DynamoForRevitNodeModels.FunctionNodes
  nameWithType: DynamoForRevitNodeModels.FunctionNodes
  fullName: DynamoForRevitNodeModels.FunctionNodes
  type: Namespace
  assemblies:
  - DynamoForRevitNodeModels
references:
- uid: DynamoForRevitNodeModels.FunctionNodes.BoundingBoxViewer
  commentId: T:DynamoForRevitNodeModels.FunctionNodes.BoundingBoxViewer
  parent: DynamoForRevitNodeModels.FunctionNodes
  isExternal: true
  href: DynamoForRevitNodeModels.FunctionNodes.BoundingBoxViewer.html
  name: BoundingBoxViewer
  nameWithType: BoundingBoxViewer
  fullName: DynamoForRevitNodeModels.FunctionNodes.BoundingBoxViewer
- uid: DynamoForRevitNodeModels.FunctionNodes.CoordinateSystemViewer
  commentId: T:DynamoForRevitNodeModels.FunctionNodes.CoordinateSystemViewer
  parent: DynamoForRevitNodeModels.FunctionNodes
  isExternal: true
  href: DynamoForRevitNodeModels.FunctionNodes.CoordinateSystemViewer.html
  name: CoordinateSystemViewer
  nameWithType: CoordinateSystemViewer
  fullName: DynamoForRevitNodeModels.FunctionNodes.CoordinateSystemViewer
- uid: DynamoForRevitNodeModels.FunctionNodes.VectorViewer
  commentId: T:DynamoForRevitNodeModels.FunctionNodes.VectorViewer
  parent: DynamoForRevitNodeModels.FunctionNodes
  isExternal: true
  href: DynamoForRevitNodeModels.FunctionNodes.VectorViewer.html
  name: VectorViewer
  nameWithType: VectorViewer
  fullName: DynamoForRevitNodeModels.FunctionNodes.VectorViewer
- uid: DynamoForRevitNodeModels.FunctionNodes.CSVRead
  commentId: T:DynamoForRevitNodeModels.FunctionNodes.CSVRead
  parent: DynamoForRevitNodeModels.FunctionNodes
  isExternal: true
  href: DynamoForRevitNodeModels.FunctionNodes.CSVRead.html
  name: CSVRead
  nameWithType: CSVRead
  fullName: DynamoForRevitNodeModels.FunctionNodes.CSVRead
- uid: DynamoForRevitNodeModels.FunctionNodes.CSVWrite
  commentId: T:DynamoForRevitNodeModels.FunctionNodes.CSVWrite
  parent: DynamoForRevitNodeModels.FunctionNodes
  isExternal: true
  href: DynamoForRevitNodeModels.FunctionNodes.CSVWrite.html
  name: CSVWrite
  nameWithType: CSVWrite
  fullName: DynamoForRevitNodeModels.FunctionNodes.CSVWrite
- uid: DynamoForRevitNodeModels.FunctionNodes.ElementParameterCreateByName
  commentId: T:DynamoForRevitNodeModels.FunctionNodes.ElementParameterCreateByName
  parent: DynamoForRevitNodeModels.FunctionNodes
  isExternal: true
  href: DynamoForRevitNodeModels.FunctionNodes.ElementParameterCreateByName.html
  name: ElementParameterCreateByName
  nameWithType: ElementParameterCreateByName
  fullName: DynamoForRevitNodeModels.FunctionNodes.ElementParameterCreateByName
- uid: DynamoForRevitNodeModels.FunctionNodes.ElementParameterCreateByBuiltInParameter
  commentId: T:DynamoForRevitNodeModels.FunctionNodes.ElementParameterCreateByBuiltInParameter
  parent: DynamoForRevitNodeModels.FunctionNodes
  isExternal: true
  href: DynamoForRevitNodeModels.FunctionNodes.ElementParameterCreateByBuiltInParameter.html
  name: ElementParameterCreateByBuiltInParameter
  nameWithType: ElementParameterCreateByBuiltInParameter
  fullName: DynamoForRevitNodeModels.FunctionNodes.ElementParameterCreateByBuiltInParameter
- uid: DynamoForRevitNodeModels.FunctionNodes.ElementParameterName
  commentId: T:DynamoForRevitNodeModels.FunctionNodes.ElementParameterName
  parent: DynamoForRevitNodeModels.FunctionNodes
  isExternal: true
  href: DynamoForRevitNodeModels.FunctionNodes.ElementParameterName.html
  name: ElementParameterName
  nameWithType: ElementParameterName
  fullName: DynamoForRevitNodeModels.FunctionNodes.ElementParameterName
- uid: DynamoForRevitNodeModels.FunctionNodes.ElementParameterValue
  commentId: T:DynamoForRevitNodeModels.FunctionNodes.ElementParameterValue
  parent: DynamoForRevitNodeModels.FunctionNodes
  isExternal: true
  href: DynamoForRevitNodeModels.FunctionNodes.ElementParameterValue.html
  name: ElementParameterValue
  nameWithType: ElementParameterValue
  fullName: DynamoForRevitNodeModels.FunctionNodes.ElementParameterValue
- uid: DynamoForRevitNodeModels.FunctionNodes.ElementParameterDataType
  commentId: T:DynamoForRevitNodeModels.FunctionNodes.ElementParameterDataType
  parent: DynamoForRevitNodeModels.FunctionNodes
  isExternal: true
  href: DynamoForRevitNodeModels.FunctionNodes.ElementParameterDataType.html
  name: ElementParameterDataType
  nameWithType: ElementParameterDataType
  fullName: DynamoForRevitNodeModels.FunctionNodes.ElementParameterDataType
- uid: DynamoForRevitNodeModels.FunctionNodes.ElementParameterKind
  commentId: T:DynamoForRevitNodeModels.FunctionNodes.ElementParameterKind
  parent: DynamoForRevitNodeModels.FunctionNodes
  isExternal: true
  href: DynamoForRevitNodeModels.FunctionNodes.ElementParameterKind.html
  name: ElementParameterKind
  nameWithType: ElementParameterKind
  fullName: DynamoForRevitNodeModels.FunctionNodes.ElementParameterKind
- uid: DynamoForRevitNodeModels.FunctionNodes.MultiReturnNodeModelBase
  commentId: T:DynamoForRevitNodeModels.FunctionNodes.MultiReturnNodeModelBase
  parent: DynamoForRevitNodeModels.FunctionNodes
  isExternal: true
  href: DynamoForRevitNodeModels.FunctionNodes.MultiReturnNodeModelBase.html
  name: MultiReturnNodeModelBase
  nameWithType: MultiReturnNodeModelBase
  fullName: DynamoForRevitNodeModels.FunctionNodes.MultiReturnNodeModelBase
- uid: DynamoForRevitNodeModels.FunctionNodes.BuiltInToUIName
  commentId: T:DynamoForRevitNodeModels.FunctionNodes.BuiltInToUIName
  parent: DynamoForRevitNodeModels.FunctionNodes
  isExternal: true
  href: DynamoForRevitNodeModels.FunctionNodes.BuiltInToUIName.html
  name: BuiltInToUIName
  nameWithType: BuiltInToUIName
  fullName: DynamoForRevitNodeModels.FunctionNodes.BuiltInToUIName
- uid: DynamoForRevitNodeModels.FunctionNodes.BuiltInCategoryToDynamoCategory
  commentId: T:DynamoForRevitNodeModels.FunctionNodes.BuiltInCategoryToDynamoCategory
  parent: DynamoForRevitNodeModels.FunctionNodes
  isExternal: true
  href: DynamoForRevitNodeModels.FunctionNodes.BuiltInCategoryToDynamoCategory.html
  name: BuiltInCategoryToDynamoCategory
  nameWithType: BuiltInCategoryToDynamoCategory
  fullName: DynamoForRevitNodeModels.FunctionNodes.BuiltInCategoryToDynamoCategory
- uid: DynamoForRevitNodeModels.FunctionNodes.SelectionBySelectionMethodAndCategory
  commentId: T:DynamoForRevitNodeModels.FunctionNodes.SelectionBySelectionMethodAndCategory
  parent: DynamoForRevitNodeModels.FunctionNodes
  isExternal: true
  href: DynamoForRevitNodeModels.FunctionNodes.SelectionBySelectionMethodAndCategory.html
  name: SelectionBySelectionMethodAndCategory
  nameWithType: SelectionBySelectionMethodAndCategory
  fullName: DynamoForRevitNodeModels.FunctionNodes.SelectionBySelectionMethodAndCategory
- uid: DynamoForRevitNodeModels.FunctionNodes.SelectionBySelectionMethodAndCategories
  commentId: T:DynamoForRevitNodeModels.FunctionNodes.SelectionBySelectionMethodAndCategories
  parent: DynamoForRevitNodeModels.FunctionNodes
  isExternal: true
  href: DynamoForRevitNodeModels.FunctionNodes.SelectionBySelectionMethodAndCategories.html
  name: SelectionBySelectionMethodAndCategories
  nameWithType: SelectionBySelectionMethodAndCategories
  fullName: DynamoForRevitNodeModels.FunctionNodes.SelectionBySelectionMethodAndCategories
- uid: DynamoForRevitNodeModels.FunctionNodes.GetSelectionResultsData
  commentId: T:DynamoForRevitNodeModels.FunctionNodes.GetSelectionResultsData
  parent: DynamoForRevitNodeModels.FunctionNodes
  isExternal: true
  href: DynamoForRevitNodeModels.FunctionNodes.GetSelectionResultsData.html
  name: GetSelectionResultsData
  nameWithType: GetSelectionResultsData
  fullName: DynamoForRevitNodeModels.FunctionNodes.GetSelectionResultsData
- uid: DynamoForRevitNodeModels.FunctionNodes.ViewCollector
  commentId: T:DynamoForRevitNodeModels.FunctionNodes.ViewCollector
  parent: DynamoForRevitNodeModels.FunctionNodes
  isExternal: true
  href: DynamoForRevitNodeModels.FunctionNodes.ViewCollector.html
  name: ViewCollector
  nameWithType: ViewCollector
  fullName: DynamoForRevitNodeModels.FunctionNodes.ViewCollector
- uid: DynamoForRevitNodeModels.FunctionNodes.StandardNodeModelBase
  commentId: T:DynamoForRevitNodeModels.FunctionNodes.StandardNodeModelBase
  parent: DynamoForRevitNodeModels.FunctionNodes
  isExternal: true
  href: DynamoForRevitNodeModels.FunctionNodes.StandardNodeModelBase.html
  name: StandardNodeModelBase
  nameWithType: StandardNodeModelBase
  fullName: DynamoForRevitNodeModels.FunctionNodes.StandardNodeModelBase
- uid: DynamoForRevitNodeModels.FunctionNodes.StandardNodeModelBaseByResources
  commentId: T:DynamoForRevitNodeModels.FunctionNodes.StandardNodeModelBaseByResources
  parent: DynamoForRevitNodeModels.FunctionNodes
  isExternal: true
  href: DynamoForRevitNodeModels.FunctionNodes.StandardNodeModelBaseByResources.html
  name: StandardNodeModelBaseByResources
  nameWithType: StandardNodeModelBaseByResources
  fullName: DynamoForRevitNodeModels.FunctionNodes.StandardNodeModelBaseByResources
- uid: DynamoForRevitNodeModels.FunctionNodes.StringFilterByRegex
  commentId: T:DynamoForRevitNodeModels.FunctionNodes.StringFilterByRegex
  parent: DynamoForRevitNodeModels.FunctionNodes
  isExternal: true
  href: DynamoForRevitNodeModels.FunctionNodes.StringFilterByRegex.html
  name: StringFilterByRegex
  nameWithType: StringFilterByRegex
  fullName: DynamoForRevitNodeModels.FunctionNodes.StringFilterByRegex
- uid: DynamoForRevitNodeModels.FunctionNodes.TopographyGetSurfaces
  commentId: T:DynamoForRevitNodeModels.FunctionNodes.TopographyGetSurfaces
  parent: DynamoForRevitNodeModels.FunctionNodes
  isExternal: true
  href: DynamoForRevitNodeModels.FunctionNodes.TopographyGetSurfaces.html
  name: TopographyGetSurfaces
  nameWithType: TopographyGetSurfaces
  fullName: DynamoForRevitNodeModels.FunctionNodes.TopographyGetSurfaces
- uid: DynamoForRevitNodeModels.FunctionNodes
  commentId: N:DynamoForRevitNodeModels.FunctionNodes
  isExternal: true
  href: DynamoForRevitNodeModels.html
  name: DynamoForRevitNodeModels.FunctionNodes
  nameWithType: DynamoForRevitNodeModels.FunctionNodes
  fullName: DynamoForRevitNodeModels.FunctionNodes
  spec.csharp:
  - uid: DynamoForRevitNodeModels
    name: DynamoForRevitNodeModels
    isExternal: true
    href: DynamoForRevitNodeModels.html
  - name: .
  - uid: DynamoForRevitNodeModels.FunctionNodes
    name: FunctionNodes
    isExternal: true
    href: DynamoForRevitNodeModels.FunctionNodes.html
  spec.vb:
  - uid: DynamoForRevitNodeModels
    name: DynamoForRevitNodeModels
    isExternal: true
    href: DynamoForRevitNodeModels.html
  - name: .
  - uid: DynamoForRevitNodeModels.FunctionNodes
    name: FunctionNodes
    isExternal: true
    href: DynamoForRevitNodeModels.FunctionNodes.html
