### YamlMime:ManagedReference
items:
- uid: DynamoForRevitUtils.Entities.Wrappers.IElementWrapper`1
  commentId: T:DynamoForRevitUtils.Entities.Wrappers.IElementWrapper`1
  id: IElementWrapper`1
  parent: DynamoForRevitUtils.Entities.Wrappers
  children:
  - DynamoForRevitUtils.Entities.Wrappers.IElementWrapper`1.Parameters
  langs:
  - csharp
  - vb
  name: IElementWrapper<TParams>
  nameWithType: IElementWrapper<TParams>
  fullName: DynamoForRevitUtils.Entities.Wrappers.IElementWrapper<TParams>
  type: Interface
  assemblies:
  - DynamoForRevitUtils
  namespace: DynamoForRevitUtils.Entities.Wrappers
  summary: Interface used to represents an Revit element wrapper with it parameters
  example: []
  syntax:
    content: >-
      [IsVisibleInDynamoLibrary(false)]

      public interface IElementWrapper<TParams> : IElementWrapper where TParams : IElementParameters
    typeParameters:
    - id: TParams
      description: Represents the type of this wrapper parameters
    content.vb: >-
      <IsVisibleInDynamoLibrary(False)>

      Public Interface IElementWrapper(Of TParams As IElementParameters) Inherits IElementWrapper
  inheritedMembers:
  - DynamoForRevitUtils.Entities.Wrappers.IElementWrapper.Element
  extensionMethods:
  - System.Object.DynamoForRevitUtils.Services.GenericServices.ObjectServices.TryCast``1
  attributes:
  - type: Autodesk.DesignScript.Runtime.IsVisibleInDynamoLibraryAttribute
    ctor: Autodesk.DesignScript.Runtime.IsVisibleInDynamoLibraryAttribute.#ctor(System.Boolean)
    arguments:
    - type: System.Boolean
      value: false
  nameWithType.vb: IElementWrapper(Of TParams)
  fullName.vb: DynamoForRevitUtils.Entities.Wrappers.IElementWrapper(Of TParams)
  name.vb: IElementWrapper(Of TParams)
- uid: DynamoForRevitUtils.Entities.Wrappers.IElementWrapper`1.Parameters
  commentId: P:DynamoForRevitUtils.Entities.Wrappers.IElementWrapper`1.Parameters
  id: Parameters
  parent: DynamoForRevitUtils.Entities.Wrappers.IElementWrapper`1
  langs:
  - csharp
  - vb
  name: Parameters
  nameWithType: IElementWrapper<TParams>.Parameters
  fullName: DynamoForRevitUtils.Entities.Wrappers.IElementWrapper<TParams>.Parameters
  type: Property
  assemblies:
  - DynamoForRevitUtils
  namespace: DynamoForRevitUtils.Entities.Wrappers
  summary: Provides access to the parameters associated with this wrapper.
  example: []
  syntax:
    content: TParams Parameters { get; }
    parameters: []
    return:
      type: '{TParams}'
    content.vb: ReadOnly Property Parameters As TParams
  overload: DynamoForRevitUtils.Entities.Wrappers.IElementWrapper`1.Parameters*
  nameWithType.vb: IElementWrapper(Of TParams).Parameters
  fullName.vb: DynamoForRevitUtils.Entities.Wrappers.IElementWrapper(Of TParams).Parameters
references:
- uid: DynamoForRevitUtils.Entities.Wrappers
  commentId: N:DynamoForRevitUtils.Entities.Wrappers
  isExternal: true
  href: DynamoForRevitUtils.html
  name: DynamoForRevitUtils.Entities.Wrappers
  nameWithType: DynamoForRevitUtils.Entities.Wrappers
  fullName: DynamoForRevitUtils.Entities.Wrappers
  spec.csharp:
  - uid: DynamoForRevitUtils
    name: DynamoForRevitUtils
    isExternal: true
    href: DynamoForRevitUtils.html
  - name: .
  - uid: DynamoForRevitUtils.Entities
    name: Entities
    isExternal: true
    href: DynamoForRevitUtils.Entities.html
  - name: .
  - uid: DynamoForRevitUtils.Entities.Wrappers
    name: Wrappers
    isExternal: true
    href: DynamoForRevitUtils.Entities.Wrappers.html
  spec.vb:
  - uid: DynamoForRevitUtils
    name: DynamoForRevitUtils
    isExternal: true
    href: DynamoForRevitUtils.html
  - name: .
  - uid: DynamoForRevitUtils.Entities
    name: Entities
    isExternal: true
    href: DynamoForRevitUtils.Entities.html
  - name: .
  - uid: DynamoForRevitUtils.Entities.Wrappers
    name: Wrappers
    isExternal: true
    href: DynamoForRevitUtils.Entities.Wrappers.html
- uid: DynamoForRevitUtils.Entities.Wrappers.IElementWrapper.Element
  commentId: P:DynamoForRevitUtils.Entities.Wrappers.IElementWrapper.Element
  parent: DynamoForRevitUtils.Entities.Wrappers.IElementWrapper
  isExternal: true
  href: DynamoForRevitUtils.Entities.Wrappers.IElementWrapper.html#DynamoForRevitUtils_Entities_Wrappers_IElementWrapper_Element
  name: Element
  nameWithType: IElementWrapper.Element
  fullName: DynamoForRevitUtils.Entities.Wrappers.IElementWrapper.Element
- uid: System.Object.DynamoForRevitUtils.Services.GenericServices.ObjectServices.TryCast``1
  commentId: M:DynamoForRevitUtils.Services.GenericServices.ObjectServices.TryCast``1(System.Object)
  parent: DynamoForRevitUtils.Services.GenericServices.ObjectServices
  definition: DynamoForRevitUtils.Services.GenericServices.ObjectServices.TryCast``1(System.Object)
  href: DynamoForRevitUtils.Services.GenericServices.ObjectServices.html#DynamoForRevitUtils_Services_GenericServices_ObjectServices_TryCast__1_System_Object_
  name: TryCast<T>(object)
  nameWithType: ObjectServices.TryCast<T>(object)
  fullName: DynamoForRevitUtils.Services.GenericServices.ObjectServices.TryCast<T>(object)
  nameWithType.vb: ObjectServices.TryCast(Of T)(Object)
  fullName.vb: DynamoForRevitUtils.Services.GenericServices.ObjectServices.TryCast(Of T)(Object)
  name.vb: TryCast(Of T)(Object)
  spec.csharp:
  - uid: DynamoForRevitUtils.Services.GenericServices.ObjectServices.TryCast``1(System.Object)
    name: TryCast
    isExternal: true
    href: DynamoForRevitUtils.Services.GenericServices.ObjectServices.html#DynamoForRevitUtils_Services_GenericServices_ObjectServices_TryCast__1_System_Object_
  - name: <
  - name: T
  - name: '>'
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: DynamoForRevitUtils.Services.GenericServices.ObjectServices.TryCast``1(System.Object)
    name: TryCast
    isExternal: true
    href: DynamoForRevitUtils.Services.GenericServices.ObjectServices.html#DynamoForRevitUtils_Services_GenericServices_ObjectServices_TryCast__1_System_Object_
  - name: (
  - name: Of
  - name: " "
  - name: T
  - name: )
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: DynamoForRevitUtils.Entities.Wrappers.IElementWrapper
  commentId: T:DynamoForRevitUtils.Entities.Wrappers.IElementWrapper
  parent: DynamoForRevitUtils.Entities.Wrappers
  isExternal: true
  href: DynamoForRevitUtils.Entities.Wrappers.IElementWrapper.html
  name: IElementWrapper
  nameWithType: IElementWrapper
  fullName: DynamoForRevitUtils.Entities.Wrappers.IElementWrapper
- uid: DynamoForRevitUtils.Services.GenericServices.ObjectServices.TryCast``1(System.Object)
  commentId: M:DynamoForRevitUtils.Services.GenericServices.ObjectServices.TryCast``1(System.Object)
  isExternal: true
  href: DynamoForRevitUtils.Services.GenericServices.ObjectServices.html#DynamoForRevitUtils_Services_GenericServices_ObjectServices_TryCast__1_System_Object_
  name: TryCast<T>(object)
  nameWithType: ObjectServices.TryCast<T>(object)
  fullName: DynamoForRevitUtils.Services.GenericServices.ObjectServices.TryCast<T>(object)
  nameWithType.vb: ObjectServices.TryCast(Of T)(Object)
  fullName.vb: DynamoForRevitUtils.Services.GenericServices.ObjectServices.TryCast(Of T)(Object)
  name.vb: TryCast(Of T)(Object)
  spec.csharp:
  - uid: DynamoForRevitUtils.Services.GenericServices.ObjectServices.TryCast``1(System.Object)
    name: TryCast
    isExternal: true
    href: DynamoForRevitUtils.Services.GenericServices.ObjectServices.html#DynamoForRevitUtils_Services_GenericServices_ObjectServices_TryCast__1_System_Object_
  - name: <
  - name: T
  - name: '>'
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: DynamoForRevitUtils.Services.GenericServices.ObjectServices.TryCast``1(System.Object)
    name: TryCast
    isExternal: true
    href: DynamoForRevitUtils.Services.GenericServices.ObjectServices.html#DynamoForRevitUtils_Services_GenericServices_ObjectServices_TryCast__1_System_Object_
  - name: (
  - name: Of
  - name: " "
  - name: T
  - name: )
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: DynamoForRevitUtils.Services.GenericServices.ObjectServices
  commentId: T:DynamoForRevitUtils.Services.GenericServices.ObjectServices
  parent: DynamoForRevitUtils.Services.GenericServices
  isExternal: true
  href: DynamoForRevitUtils.Services.GenericServices.ObjectServices.html
  name: ObjectServices
  nameWithType: ObjectServices
  fullName: DynamoForRevitUtils.Services.GenericServices.ObjectServices
- uid: DynamoForRevitUtils.Services.GenericServices
  commentId: N:DynamoForRevitUtils.Services.GenericServices
  isExternal: true
  href: DynamoForRevitUtils.html
  name: DynamoForRevitUtils.Services.GenericServices
  nameWithType: DynamoForRevitUtils.Services.GenericServices
  fullName: DynamoForRevitUtils.Services.GenericServices
  spec.csharp:
  - uid: DynamoForRevitUtils
    name: DynamoForRevitUtils
    isExternal: true
    href: DynamoForRevitUtils.html
  - name: .
  - uid: DynamoForRevitUtils.Services
    name: Services
    isExternal: true
    href: DynamoForRevitUtils.Services.html
  - name: .
  - uid: DynamoForRevitUtils.Services.GenericServices
    name: GenericServices
    isExternal: true
    href: DynamoForRevitUtils.Services.GenericServices.html
  spec.vb:
  - uid: DynamoForRevitUtils
    name: DynamoForRevitUtils
    isExternal: true
    href: DynamoForRevitUtils.html
  - name: .
  - uid: DynamoForRevitUtils.Services
    name: Services
    isExternal: true
    href: DynamoForRevitUtils.Services.html
  - name: .
  - uid: DynamoForRevitUtils.Services.GenericServices
    name: GenericServices
    isExternal: true
    href: DynamoForRevitUtils.Services.GenericServices.html
- uid: DynamoForRevitUtils.Entities.Wrappers.IElementWrapper`1.Parameters*
  commentId: Overload:DynamoForRevitUtils.Entities.Wrappers.IElementWrapper`1.Parameters
  isExternal: true
  href: DynamoForRevitUtils.Entities.Wrappers.IElementWrapper-1.html#DynamoForRevitUtils_Entities_Wrappers_IElementWrapper_1_Parameters
  name: Parameters
  nameWithType: IElementWrapper<TParams>.Parameters
  fullName: DynamoForRevitUtils.Entities.Wrappers.IElementWrapper<TParams>.Parameters
  nameWithType.vb: IElementWrapper(Of TParams).Parameters
  fullName.vb: DynamoForRevitUtils.Entities.Wrappers.IElementWrapper(Of TParams).Parameters
- uid: '{TParams}'
  commentId: '!:TParams'
  definition: TParams
  name: TParams
  nameWithType: TParams
  fullName: TParams
- uid: TParams
  name: TParams
  nameWithType: TParams
  fullName: TParams
