### YamlMime:TableOfContent
items:
- uid: DynamoForRevitUtils.Constants
  name: DynamoForRevitUtils.Constants
  type: Namespace
  items:
  - uid: DynamoForRevitUtils.Constants.Common
    name: Common
    type: Class
- uid: DynamoForRevitUtils.Entities
  name: DynamoForRevitUtils.Entities
  type: Namespace
  items:
  - uid: DynamoForRevitUtils.Entities.Axis
    name: Axis
    type: Class
  - uid: DynamoForRevitUtils.Entities.CompoundStructureLayersInfo
    name: CompoundStructureLayersInfo
    type: Class
  - uid: DynamoForRevitUtils.Entities.CropRegionOffsetSettings
    name: CropRegionOffsetSettings
    type: Class
  - uid: DynamoForRevitUtils.Entities.GetUnitsResultData
    name: GetUnitsResultData
    type: Class
  - uid: DynamoForRevitUtils.Entities.MEPCurveReferences
    name: MEPCurveReferences
    type: Class
  - uid: DynamoForRevitUtils.Entities.Section
    name: Section
    type: Class
  - uid: DynamoForRevitUtils.Entities.SectionCreationData
    name: SectionCreationData
    type: Class
  - uid: DynamoForRevitUtils.Entities.SelectionResults
    name: SelectionResults
    type: Class
  - uid: DynamoForRevitUtils.Entities.SelectionSettings
    name: SelectionSettings
    type: Class
  - uid: DynamoForRevitUtils.Entities.WallElevation
    name: WallElevation
    type: Class
- uid: DynamoForRevitUtils.Entities.AbstractGeometry
  name: DynamoForRevitUtils.Entities.AbstractGeometry
  type: Namespace
  items:
  - uid: DynamoForRevitUtils.Entities.AbstractGeometry.AbstractBoundingBox
    name: AbstractBoundingBox
    type: Class
  - uid: DynamoForRevitUtils.Entities.AbstractGeometry.AbstractCoordinateSystem
    name: AbstractCoordinateSystem
    type: Class
  - uid: DynamoForRevitUtils.Entities.AbstractGeometry.AbstractGeometryBase`1
    name: AbstractGeometryBase<T>
    type: Class
  - uid: DynamoForRevitUtils.Entities.AbstractGeometry.AbstractGeometryFactory
    name: AbstractGeometryFactory
    type: Class
  - uid: DynamoForRevitUtils.Entities.AbstractGeometry.AbstractVector
    name: AbstractVector
    type: Class
  - uid: DynamoForRevitUtils.Entities.AbstractGeometry.IAbstractGeometry
    name: IAbstractGeometry
    type: Interface
- uid: DynamoForRevitUtils.Entities.EqualityComparers
  name: DynamoForRevitUtils.Entities.EqualityComparers
  type: Namespace
  items:
  - uid: DynamoForRevitUtils.Entities.EqualityComparers.ElementComparer
    name: ElementComparer
    type: Class
  - uid: DynamoForRevitUtils.Entities.EqualityComparers.ElementReferenceComparer
    name: ElementReferenceComparer
    type: Class
- uid: DynamoForRevitUtils.Entities.ParametersHandlers
  name: DynamoForRevitUtils.Entities.ParametersHandlers
  type: Namespace
  items:
  - uid: DynamoForRevitUtils.Entities.ParametersHandlers.AccessElementParameterOptions
    name: AccessElementParameterOptions
    type: Class
  - uid: DynamoForRevitUtils.Entities.ParametersHandlers.AccessParameterInfo
    name: AccessParameterInfo
    type: Class
  - uid: DynamoForRevitUtils.Entities.ParametersHandlers.ElementParameter
    name: ElementParameter
    type: Class
  - uid: DynamoForRevitUtils.Entities.ParametersHandlers.ElementParameterAccessor`1
    name: ElementParameterAccessor<TParamMap>
    type: Class
  - uid: DynamoForRevitUtils.Entities.ParametersHandlers.ElementParameterMapItem
    name: ElementParameterMapItem
    type: Class
  - uid: DynamoForRevitUtils.Entities.ParametersHandlers.ElementParameterMap`1
    name: ElementParameterMap<T>
    type: Class
  - uid: DynamoForRevitUtils.Entities.ParametersHandlers.IElementParameterMap
    name: IElementParameterMap
    type: Interface
- uid: DynamoForRevitUtils.Entities.PickSelectionFilters
  name: DynamoForRevitUtils.Entities.PickSelectionFilters
  type: Namespace
  items:
  - uid: DynamoForRevitUtils.Entities.PickSelectionFilters.CategorySelectionFilter
    name: CategorySelectionFilter
    type: Class
  - uid: DynamoForRevitUtils.Entities.PickSelectionFilters.MultiCategorySelectionFilter
    name: MultiCategorySelectionFilter
    type: Class
  - uid: DynamoForRevitUtils.Entities.PickSelectionFilters.NoFilter
    name: NoFilter
    type: Class
  - uid: DynamoForRevitUtils.Entities.PickSelectionFilters.PickSelectionFilter
    name: PickSelectionFilter
    type: Class
  - uid: DynamoForRevitUtils.Entities.PickSelectionFilters.WallSelectionFilter
    name: WallSelectionFilter
    type: Class
- uid: DynamoForRevitUtils.Entities.Wrappers
  name: DynamoForRevitUtils.Entities.Wrappers
  type: Namespace
  items:
  - uid: DynamoForRevitUtils.Entities.Wrappers.ElementWrapper`1
    name: ElementWrapper<TParamMap>
    type: Class
  - uid: DynamoForRevitUtils.Entities.Wrappers.FamilyInstanceWrapper`1
    name: FamilyInstanceWrapper<TParamMap>
    type: Class
  - uid: DynamoForRevitUtils.Entities.Wrappers.IElementWrapper`1
    name: IElementWrapper<TParamMap>
    type: Interface
- uid: DynamoForRevitUtils.Enumerations
  name: DynamoForRevitUtils.Enumerations
  type: Namespace
  items:
  - uid: DynamoForRevitUtils.Enumerations.AccessParameterMode
    name: AccessParameterMode
    type: Enum
  - uid: DynamoForRevitUtils.Enumerations.AccessParameterResult
    name: AccessParameterResult
    type: Enum
  - uid: DynamoForRevitUtils.Enumerations.Coordinate
    name: Coordinate
    type: Enum
  - uid: DynamoForRevitUtils.Enumerations.DoubleParameterConvertionMode
    name: DoubleParameterConvertionMode
    type: Enum
  - uid: DynamoForRevitUtils.Enumerations.ElementParameterYesNoValue
    name: ElementParameterYesNoValue
    type: Enum
  - uid: DynamoForRevitUtils.Enumerations.ParameterDataType
    name: ParameterDataType
    type: Enum
  - uid: DynamoForRevitUtils.Enumerations.ParameterKind
    name: ParameterKind
    type: Enum
  - uid: DynamoForRevitUtils.Enumerations.ParameterValidationResult
    name: ParameterValidationResult
    type: Enum
  - uid: DynamoForRevitUtils.Enumerations.RoofLineType
    name: RoofLineType
    type: Enum
  - uid: DynamoForRevitUtils.Enumerations.SelectionMethod
    name: SelectionMethod
    type: Enum
- uid: DynamoForRevitUtils.Services.Collections
  name: DynamoForRevitUtils.Services.Collections
  type: Namespace
  items:
  - uid: DynamoForRevitUtils.Services.Collections.EnumerableServices
    name: EnumerableServices
    type: Class
- uid: DynamoForRevitUtils.Services.Collectors
  name: DynamoForRevitUtils.Services.Collectors
  type: Namespace
  items:
  - uid: DynamoForRevitUtils.Services.Collectors.CategoryCollectors
    name: CategoryCollectors
    type: Class
  - uid: DynamoForRevitUtils.Services.Collectors.GenericCollectors
    name: GenericCollectors
    type: Class
  - uid: DynamoForRevitUtils.Services.Collectors.LineStyleCollectors
    name: LineStyleCollectors
    type: Class
  - uid: DynamoForRevitUtils.Services.Collectors.PhaseCollectors
    name: PhaseCollectors
    type: Class
  - uid: DynamoForRevitUtils.Services.Collectors.RoomCollectors
    name: RoomCollectors
    type: Class
  - uid: DynamoForRevitUtils.Services.Collectors.WallCollectors
    name: WallCollectors
    type: Class
- uid: DynamoForRevitUtils.Services.Dynamo
  name: DynamoForRevitUtils.Services.Dynamo
  type: Namespace
  items:
  - uid: DynamoForRevitUtils.Services.Dynamo.BoundingBoxServices
    name: BoundingBoxServices
    type: Class
  - uid: DynamoForRevitUtils.Services.Dynamo.DynamoGeometryServices
    name: DynamoGeometryServices
    type: Class
  - uid: DynamoForRevitUtils.Services.Dynamo.JoinLinesServices
    name: JoinLinesServices
    type: Class
  - uid: DynamoForRevitUtils.Services.Dynamo.RevitElementsServices
    name: RevitElementsServices
    type: Class
  - uid: DynamoForRevitUtils.Services.Dynamo.TopographyServices
    name: TopographyServices
    type: Class
- uid: DynamoForRevitUtils.Services.Enumerations
  name: DynamoForRevitUtils.Services.Enumerations
  type: Namespace
  items:
  - uid: DynamoForRevitUtils.Services.Enumerations.Converters
    name: Converters
    type: Class
  - uid: DynamoForRevitUtils.Services.Enumerations.EnumParser
    name: EnumParser
    type: Class
- uid: DynamoForRevitUtils.Services.Files
  name: DynamoForRevitUtils.Services.Files
  type: Namespace
  items:
  - uid: DynamoForRevitUtils.Services.Files.CSV
    name: CSV
    type: Class
  - uid: DynamoForRevitUtils.Services.Files.Excel
    name: Excel
    type: Class
- uid: DynamoForRevitUtils.Services.GenericServices
  name: DynamoForRevitUtils.Services.GenericServices
  type: Namespace
  items:
  - uid: DynamoForRevitUtils.Services.GenericServices.ObjectServices
    name: ObjectServices
    type: Class
- uid: DynamoForRevitUtils.Services.MathServices
  name: DynamoForRevitUtils.Services.MathServices
  type: Namespace
  items:
  - uid: DynamoForRevitUtils.Services.MathServices.ArithmeticServices
    name: ArithmeticServices
    type: Class
  - uid: DynamoForRevitUtils.Services.MathServices.LinearAlgebraServices
    name: LinearAlgebraServices
    type: Class
  - uid: DynamoForRevitUtils.Services.MathServices.RangeServices
    name: RangeServices
    type: Class
  - uid: DynamoForRevitUtils.Services.MathServices.SequenceServices
    name: SequenceServices
    type: Class
- uid: DynamoForRevitUtils.Services.Reflection
  name: DynamoForRevitUtils.Services.Reflection
  type: Namespace
  items:
  - uid: DynamoForRevitUtils.Services.Reflection.ReflectionServices
    name: ReflectionServices
    type: Class
- uid: DynamoForRevitUtils.Services.RevitServices
  name: DynamoForRevitUtils.Services.RevitServices
  type: Namespace
  items:
  - uid: DynamoForRevitUtils.Services.RevitServices.CategoryServices
    name: CategoryServices
    type: Class
  - uid: DynamoForRevitUtils.Services.RevitServices.DesignOptionServices
    name: DesignOptionServices
    type: Class
  - uid: DynamoForRevitUtils.Services.RevitServices.DocumentServices
    name: DocumentServices
    type: Class
  - uid: DynamoForRevitUtils.Services.RevitServices.ElementIdServices
    name: ElementIdServices
    type: Class
  - uid: DynamoForRevitUtils.Services.RevitServices.ElementServices
    name: ElementServices
    type: Class
  - uid: DynamoForRevitUtils.Services.RevitServices.FamilyInstanceServices
    name: FamilyInstanceServices
    type: Class
  - uid: DynamoForRevitUtils.Services.RevitServices.GridServices
    name: GridServices
    type: Class
  - uid: DynamoForRevitUtils.Services.RevitServices.ImportInstanceServices
    name: ImportInstanceServices
    type: Class
  - uid: DynamoForRevitUtils.Services.RevitServices.LevelServices
    name: LevelServices
    type: Class
  - uid: DynamoForRevitUtils.Services.RevitServices.MEPCurveServices
    name: MEPCurveServices
    type: Class
  - uid: DynamoForRevitUtils.Services.RevitServices.RevitGeometryServices
    name: RevitGeometryServices
    type: Class
  - uid: DynamoForRevitUtils.Services.RevitServices.TagCreationService
    name: TagCreationService
    type: Class
  - uid: DynamoForRevitUtils.Services.RevitServices.TagInfo
    name: TagInfo
    type: Class
  - uid: DynamoForRevitUtils.Services.RevitServices.TaskDialogServices
    name: TaskDialogServices
    type: Class
  - uid: DynamoForRevitUtils.Services.RevitServices.ViewServices
    name: ViewServices
    type: Class
  - uid: DynamoForRevitUtils.Services.RevitServices.WallServices
    name: WallServices
    type: Class
- uid: DynamoForRevitUtils.Services.UnitsConversion
  name: DynamoForRevitUtils.Services.UnitsConversion
  type: Namespace
  items:
  - uid: DynamoForRevitUtils.Services.UnitsConversion.ConversionServices
    name: ConversionServices
    type: Class
  - uid: DynamoForRevitUtils.Services.UnitsConversion.SpecificFactorsServices
    name: SpecificFactorsServices
    type: Class
  - uid: DynamoForRevitUtils.Services.UnitsConversion.UnitsServices
    name: UnitsServices
    type: Class
memberLayout: SamePage
